### ISSUE TITLE
textAreaInput width can not work

### ISSUE THREAD

**Issue by goushixue** [RinteRface/bs4Dash#103]
Hi,
I find it is not work when I want to set the width of textAreaInput. is there anything wrong ?
In my Rstudio, the command is:
```
textAreaInput("input_gene", "Input genes:", rows = 3, width = "100%")
```
but in my shinyApp, it shows:
![未命名](https://user-images.githubusercontent.com/37802226/80556304-bc7d0180-8a05-11ea-9a18-9cc803349532.png)

I'm sorry that the picture can't uploaded.
It seems that the width is fixed and can't be change.

**Comment by DivadNojnarg** [comment]
Thanks for the report.

**Comment by DivadNojnarg** [comment]
Fixed in latest development version!

```r
library(shiny)
library(bs4Dash)
shinyApp(
  ui = dashboardPage(
    dashboardHeader(),
    dashboardSidebar(),
    dashboardBody(
      box(
        solidHeader = FALSE,
        title = "Status summary",
        background = NULL,
        width = 12,
        status = "danger",
        textAreaInput("input_gene", "Input genes:", rows = 3, width = "100%")
      )
    ),
    title = "Description Blocks"
  ),
  server = function(input, output) { }
)
```
