### ISSUE TITLE
suggestion for improvement of bs4SidebarHeader ()

### ISSUE THREAD

**Issue by dssrw** [RinteRface/bs4Dash#104]
it would be great if you hide the sidebar on the left side by clicking on the hide button, the bs4SidebarHeader would not get lost in the left menu. Also it would be nice when with mouseover the left menu expands the bs4SidebarHeader is be displayed also in this view

**Comment by DivadNojnarg** [comment]
This is something due to the HTML template bs4Dash is based on. I could change it but it might be an issue for future update as it may break easily.
