### ISSUE TITLE
improvement of the bs4SidebarMenu ()

### ISSUE THREAD

**Issue by dssrw** [RinteRface/bs4Dash#105]
if you have a very long sidebar menu, the whole page starts to scroll down.
if you click on one item in the bs4SidebarMenuItem, the selected page in body -> bs4TabItems() also scrolls down and only the lower part of the page is visible, which is not practical. 

it would be better if the sidebarmenu on the left gets a scrollbar if it is higher than the page itself, then there would not be this problem

is solved it simple for now with this add on change of tab .. check the pseudocode

>  observeEvent(input$dashsidebar_has_changed,{
> shinyjs::runjs("window.scrollTo(0, 0)")
> })

**Comment by analytichealth** [comment]
Related to: #69

**Comment by DivadNojnarg** [comment]
Fixed in latest devel version as well as #69 . Thanks!
