### ISSUE TITLE
bs4usermenu render name

### ISSUE THREAD

**Issue by tdecers** [RinteRface/bs4Dash#106]
Hi David,

Thanks for all your work. The bs4dash package is very pretty.

I can't find a solution to align image from src and text from name in bs4usermenu when I want to render the name via a textOutput for example.  
If I write name = "My Name", image from src and text from name are aligned on the same line.  
If I write name = textOutput("rendername"), image from src and text are on 2 differents lines because the current function bs4usermenu create special div for name, with rendername a renderText with the name of who is log on.  

Here is the html output from the function :   
With fixed name :  
`<span class="d-none d-md-inline">My name</span>`  
With rendered name :  
`<span class="d-none d-md-inline">`  
`<div id="name" class="shiny-text-output shiny-bound-output">My name</div>`  
`</span>`  

When I force the html code, the div size is not respected and I can't find where you resize the div behind the img size.

Best regards.  

Thomas

**Comment by DivadNojnarg** [comment]
With uiOutput you can play with the inline parameter and use span instead of div.

**Comment by tdecers** [comment]
Thank you David.

In fact, just `<ul class="navbar-nav ml-auto">` missed at the beginning of my uiOutput to well include the uiOutput in the content of navbar-nav.
Maybe you could change something in bs4UserMenu function to generate juste one span in 'd-'none d-md-inline' when the argument name = textOutput("myname") instead of one span and one div.

Thanks again for all you do for the community.
