### ISSUE TITLE
Sidebar Width ?

### ISSUE THREAD

**Issue by stephLH** [RinteRface/bs4Dash#11]
Is there a way to define the sidebar width ? (Like in shinydashboard)

Maybe you have an example with custom CSS ?

**Comment by DivadNojnarg** [comment]
which sidebar: The left or the right one?

**Comment by DivadNojnarg** [comment]
For the right sidebar, this should be quite easy, adding the width argument. I also need to change the width when the sidebar is collapsed.
For the left one, I have to see in detail but should not be really hard as well
I will push tomorrow

**Comment by DivadNojnarg** [comment]
I pushed something to control the size of the `bs4DashControlbar()`. Things are more complex than I thought for the main sidebar so I still do not have a fully working solution.

**Comment by stephLH** [comment]
Thank you David, the controlBar width works perfectly.

**Comment by gueyenono** [comment]
@DivadNojnarg How about you close this issue?  👍

**Comment by DivadNojnarg** [comment]
This feature is still missing for the main sidebar.

**Comment by sailogeshh** [comment]
bs4DashSidebar(  tags$style(HTML(" .main-sidebar{  width: 550px;  }" ))  )

hope it will works.

**Comment by ajmoralesa** [comment]
> bs4DashSidebar( tags$style(HTML(" .main-sidebar{ width: 550px; }" )) )
> 
> hope it will works.

It does change sidebar width but it remains fixed and it cannot be hidden

**Comment by DivadNojnarg** [comment]
Fixed in latest development version

**Comment by RaphBil** [comment]
@DivadNojnarg can you please precise which dev version you are referring to? v2.0?
If yes, is there a way to control the sidebar width with v.0.5 without loosing the hidden option? 

Thanks!

**Comment by wadetsl** [comment]
I found an R package to be perfect for correcting these errors ：**fresh**
https://dreamrs.github.io/fresh/reference/bs4dash_layout.html
How to fix the sidebar is described in detail in this link
such as：
  use_theme(create_theme(bs4dash_layout(sidebar_width = "300px")))
But it must be placed next to the bs4DashBody function！！！

**Comment by bpb824** [comment]
The fresh trick above solved my issue, but would be great if the `width` parameter in the `bs4DashControlBar()` function worked...
