### ISSUE TITLE
deactivate / disable tooltip

### ISSUE THREAD

**Issue by stevepowell99** [RinteRface/bs4Dash#117]
I can activate a tooltip for a specific item like this:

`bs4TooltipServer(selector = "#top_row",options = list(title = "my title",placement = "auto"))`

but how do I switch it off again?

`bs4TooltipServer(selector = "#top_row",options = list(title = "",placement = "auto"))`

has no effect. In fact I can't even change the tooltip:

`bs4TooltipServer(selector = "#top_row",options = list(title = "new title",placement = "auto"))`

also has no effect.

**Comment by liubomyrgavryliv** [comment]
$(".tooltiptextx").css({"visibility": "hidden"}) - turns tooltips off
$(".tooltiptextx").css({"visibility": ""}) - turns tooltips on

**Comment by DivadNojnarg** [comment]
Fixed in v2.0.0
