### ISSUE TITLE
Layout for filling the page

### ISSUE THREAD

**Issue by Uriahf** [RinteRface/bs4Dash#120]
Is there a way to make the cards in the bs4Dash body to fill the page the same way some layouts do that on flexdashboard?
https://rmarkdown.rstudio.com/flexdashboard/layouts.html#chart_stack_(fill)

Thanks!

**Comment by mattfemia** [comment]
Hey @Uriahf, do you have a reprex?

This should be possible using the width argument:

`bs4Card(inputId, width=12)`

If you need to use several in a grid like the example you sent, you can embed cards inside a combination of `shiny::fluidRow()` and `shiny::column()` to achieve the same effect. For example:


`fluidRow(
                   column(12,
                        bs4Card(inputId, width=12)
                    )
),
fluidRow(
                   column(12,
                        bs4Card(inputId, width=12)
                    )
)  
`
