### ISSUE TITLE
Content for bs4SidebarMenuItem() that has child items

### ISSUE THREAD

**Issue by vorpalvorpal** [RinteRface/bs4Dash#121]
G'day,

If a bs4SidebarMenuItem has child bs4SidebarMenuItem or bs4SidebarMenuSubItem, then the tab associated with the parent menu item is no longer accessible. If it was only the arrow rather the entire menu item button that controlled the folding of the child menu items, then the rest of the button could be act as normal to display the tab content.

I'm not sure if this is a limitation of bs4Dash or of the underlying AdminLTE3 code.

All the best.

**Comment by DivadNojnarg** [comment]
This is related to the underlying AdminLTE3 code.
