### ISSUE TITLE
solidHeader is not working in bs4Card

### ISSUE THREAD

**Issue by bajahranks** [RinteRface/bs4Dash#127]
Attempting to add a card using an example from the bs4Card documentation, I noticed that the solidHeader property is not working as expected. Every other property works except the solidHeader. See image below of the result of the code below. 
```
fluidRow(
    bs4Card(
      title = "Closable Box with solidHeader", 
      closable = TRUE, 
      width = 6,
      solidHeader = TRUE, 
      status = "primary",
      collapsible = TRUE,
      p("Box Content")
    )
  )
```
![image](https://user-images.githubusercontent.com/24802231/89143064-45309f80-d517-11ea-9609-c12dcd61b6aa.png)

**Comment by DivadNojnarg** [comment]
This is an (stupid) error I made at the very beginning of the package development. It will be fixed in a new release.

**Comment by bajahranks** [comment]
Looking forward to the new release.
