### ISSUE TITLE
Issue with updatebs4Tabitems

### ISSUE THREAD

**Issue by B-Fernandez** [RinteRface/bs4Dash#133]
In the example of updating the selected tab, the tab update does not seem to work. This is both on the UI side and the value held on the server side by 'input$sidebar'.

https://rinterface.github.io/bs4Dash/reference/updatebs4TabItems.html

I am not sure if it is related to this issue [(https://github.com/RinteRface/bs4Dash/issues/8)] although underscores have not been used in neither the example or in my workings.

I have tried using the underlying sendCustomMessage but am not able to change the actual value.
Any suggestion is helpful!

**Comment by DivadNojnarg** [comment]
Fixed in v2.0.0

**Comment by B-Fernandez** [comment]
Thanks for this - will check in.

**Comment by James-G-Hill** [comment]
Has this been confirmed as fixed?

I cannot get `updateTabItems` to work on `bs4Dash` v2.  I assume that the result should be to change the currently selected tab?  I'm somewhat unclear as to what the variables 'inputId' and 'selected' refer to; is 'inputId' the `sidebarMenu` 'id' value and 'selected' the `menuItem` 'tabName' value?
