### ISSUE TITLE
Opening the right sidebar doesn't trigger resize event

### ISSUE THREAD

**Issue by ismirsehregal** [RinteRface/bs4Dash#134]
Coming from [here](https://stackoverflow.com/questions/63839635/move-the-footer-at-the-bottom-of-a-dt-in-shiny-r).

bs4Dash seems to have the same behaviour as [shinydashboardPlus ](https://github.com/RinteRface/shinydashboardPlus/issues/86) by default:

![image](https://user-images.githubusercontent.com/36849480/93210664-47b22600-f760-11ea-9fdf-f14e3469f016.png)

**Comment by DivadNojnarg** [comment]
Are you using the CRAN or github version?

**Comment by ismirsehregal** [comment]
For the above I was using the latest CRAN version.

I just switched to the latest GitHub version (0.6.0.9000) and the behaviour changed, but it seems there still is something wrong:

![screen](https://user-images.githubusercontent.com/36849480/95962761-17b17d80-0e07-11eb-96de-89cef6d33c75.gif)

The left sidebar doesn't collapse on every click and the plot doesn't properly resize when expanding the right sidebar.

```
library(shiny)
library(bs4Dash)

ui = bs4DashPage(
  old_school = FALSE,
  sidebar_min = TRUE,
  sidebar_collapsed = FALSE,
  controlbar_collapsed = FALSE,
  controlbar_overlay = TRUE,
  title = "Basic Dashboard",
  navbar = bs4DashNavbar(),
  sidebar = bs4DashSidebar(),
  controlbar = bs4DashControlbar(),
  footer = bs4DashFooter(),
  body = bs4DashBody(plotOutput("myPlot", width = "100%"))
)

server = function(input, output, session) {
  output$myPlot = renderPlot({
    plot(1:10)
  })
}

shinyApp(ui, server)
```
