### ISSUE TITLE
sidebar issue with fresh package

### ISSUE THREAD

**Issue by psychometrician** [RinteRface/bs4Dash#136]
![2020-10-26_22-41-10](https://user-images.githubusercontent.com/3190035/97254529-92ea3a80-17dc-11eb-83cb-bb19568bb55b.png)

There is some sidebar issue when I used fresh package. I am not sure it is fresh issue or bs4Dash.  The sidebar doesn't extend to bottom. When I remove 
        use_theme(
           create_theme(
            bs4dash_status(
              success = "#849A3F",
              danger = "#F26D3A",
              primary = "#007599",
              warning="#F5D768"
            )
          )
   )
from bs4DashBody, the sidebar properly extends to the bottom.

**Comment by DivadNojnarg** [comment]
Tested with V2.0.0 and works well:

```r
devtools::install_github("RinteRface/bs4Dash")
library(shiny)
library(bs4Dash)
library(fresh)
shinyApp(
  ui = dashboardPage(
    freshTheme = create_theme(
      bs4dash_status(
        success = "#849A3F",
        danger = "#F26D3A",
        primary = "#007599",
        warning = "#F5D768"
      )
    ),
    header = dashboardHeader(
      title = dashboardBrand(
        title = "My dashboard",
        color = "primary",
        href = "https://adminlte.io/themes/v3",
        image = "https://adminlte.io/themes/v3/dist/img/AdminLTELogo.png"
      )
    ),
    sidebar = dashboardSidebar(),
    body = dashboardBody(
      box(status = "danger"),
      box(status = "primary"),
      box(status = "orange")
    ),
    controlbar = dashboardControlbar(),
    title = "DashboardPage"
  ),
  server = function(input, output) { }
)
```

**Comment by DivadNojnarg** [comment]
@pvictor : maybe we should bump fresh AdminLTE deps to align with bs4Dash v 2.0.0 once release on CRAN?
