### ISSUE TITLE
not default HTML output file defined; please call HTMLSetFile() to set it

### ISSUE THREAD

**Issue by MuzyAce** [RinteRface/bs4Dash#138]
I try to run bs4DashGallery but return "Error in HTMLGetFile() : not default HTML output file defined; please call HTMLSetFile() to set it"

**Comment by DivadNojnarg** [comment]
This issue is not related to `{bs4Dash}`: https://www.rdocumentation.org/packages/R2HTML/versions/2.3.2/topics/HTMLInitFile
