### ISSUE TITLE
release bs4Dash 2.0.0 on CRAN

### ISSUE THREAD

**Issue by DivadNojnarg** [RinteRface/bs4Dash#144]
Need to wait dependencies to go on CRAN first (shiny, bslib, ...)

**Comment by obenno** [comment]
Hi,

Since the API changes a lot, may I ask where to find the documents of 2.0 version? Thanks.

**Comment by DivadNojnarg** [comment]
The work in progress documentation is here: https://bs4dash.rinterface.com/index.html

**Comment by obenno** [comment]
Thank you for the link, it's amazing!

**Comment by mattwarkentin** [comment]
Any updates on when this might go to CRAN? Amazing work, by the way.

**Comment by DivadNojnarg** [comment]
When {shiny} 1.6, {bslib} reach the CRAN, next week probably. So I'll submit in a least 2 weeks.

**Comment by DivadNojnarg** [comment]
Taking delay because of the buggy `updateBox` function. Still need to align with `{shinydashboardPlus}` ...

**Comment by nicholaelaw** [comment]
Just asking, do I have to worry about this ```updateBox``` probelm if I do not use ```{shinydashboardPlus}```?

**Comment by DivadNojnarg** [comment]
`updateBox` has been aligned and fixed. Now I am polishing the documentation
