### ISSUE TITLE
Adding CSS file is not working

### ISSUE THREAD

**Issue by kmaheshkulkarni** [RinteRface/bs4Dash#145]
```
tags$head(
      tags$link(
        rel = "stylesheet",
        type = "text/css",
        href = "pdash.css"
      )
    ),
```

### The above code is not working

**Comment by kmaheshkulkarni** [comment]
>  Just add **.css** file to **freshTheme** as mention below


```
shinyApp(
  ui = dashboardPage(

    freshTheme = "pdash.css"

    header = dashboardHeader( ),
    body = dashboardBody(
    
),
    sidebar = dashboardSidebar()
  ),
  server = function(input, output, session) {
    
  }
)
```

**Comment by DivadNojnarg** [comment]
Oh I see, maybe you added the css to dashboardPage... Actually, it should be added to `dashboardBody`

**Comment by kmaheshkulkarni** [comment]
> Oh I see, maybe you added the css to dashboardPage... Actually, it should be added to `dashboardBody`

> I have tried it in `dashboardBody()` also but I got the same errors. Finally, I came with the above solution
**I suggest you add the above code as an example to somewhere in the bs4dash site**
> What do you think ?
