### ISSUE TITLE
MathJax with bs4Dash 2.0.0

### ISSUE THREAD

**Issue by dwoll** [RinteRface/bs4Dash#149]
First of all, many thanks for this great package! It allows to really easily create very polished output. I'm currently in the process of making all my shiny apps ready for bs4Dash version 2.0.0, and I've encountered the following issue:

In bs4Dash version 0.5, it was possible to use `shiny::withMathJax()` inside of `bs4DashPage()`, while I've had no success in placing it inside of `dashboardPage()`. What is the canonical way to enable MathJax in bs4Dash version 2.0.0? Thanks in advance!

**Comment by DivadNojnarg** [comment]
Hi. This example works well for me:

```r
library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    header = dashboardHeader(),
    body = dashboardBody(withMathJax(helpText("Some math here $$\\alpha+\\beta$$"))),
    sidebar = dashboardSidebar()
  ),
  server = function(input, output) {}
)
```

**Comment by dwoll** [comment]
Perfect, thank you!
