### ISSUE TITLE
Menu with subitems defined into server

### ISSUE THREAD

**Issue by DavideMassidda** [RinteRface/bs4Dash#150]
I'm building a shiny app with a server-side defined sidebar menu. This is a mandatory condition for me, because in future developments the menu will have to be responsive to server side events.

I'm using `shiny 1.5.0`, `shinydashboard 0.7.1` and `bs4Dash 2.0.0.9000` under `R 4.0.2` on Windows 10 x64.

This is the code of the app using shinydashboard.

```
library("shiny")
library("shinydashboard") # library("bs4Dash")
ui <- dashboardPage(
    header = dashboardHeader(),
    sidebar = dashboardSidebar(uiOutput("sidebar")),
    body = dashboardBody(uiOutput("body"))
)
server <- function(session, input, output) {
    output$mainmenu <- renderMenu({
        sidebarMenu(
            menuItem(text = "Item A",
                menuSubItem(text = "Submenu 1", tabName = "item_A1"),
                menuSubItem(text = "Submenu 2", tabName = "item_A2")
            ),
            menuItem(text = "Item B", tabName = "item_B")
        )
    })
    output$sidebar <- renderUI({
        sidebarMenuOutput("mainmenu")
    })
    output$body <- renderUI({
        tabItems(
            tabItem(tabName = "item_A1", p("First page")),
            tabItem(tabName = "item_A2", p("Second page")),
            tabItem(tabName = "item_B", p("Third page"))
        )
    })
}
shinyApp(ui, server)
```

The side menu includes a submenu. The problem is that when I use `shinydashboard`, the code works as expected. However, switching to `bs4Dash`, the menu it's no longer responsive. How can I solve?

Thank you very much!

**Comment by DivadNojnarg** [comment]
Hi Davide,

thanks for spotting this issue. This was annoying. Hopefully this is fixed now with latest devel version.
