### ISSUE TITLE
Disable scroll to top button

### ISSUE THREAD

**Issue by fmmattioni** [RinteRface/bs4Dash#152]
Hey @DivadNojnarg!

I was wondering if I could somehow disable the button on the right bottom corner that scrolls to the top? The reason for that is that I have a few links in my right side footer and the button overlays one of the links.

Screenshot:

![image](https://user-images.githubusercontent.com/36630619/103233781-37ecd500-493e-11eb-9c7d-3dfeaff612f4.png)

Thanks in advance!
Felipe

**Comment by psychometrician** [comment]
I was about to request the same thing. I use shinymanger to manage shiny app users. The logout button is located at the same position where the scrolls-to-the-top button from bs4Dash is.

**Comment by DivadNojnarg** [comment]
Added a `scrollToTop` param to `dashboardPage`

**Comment by fmmattioni** [comment]
Thanks a lot, @DivadNojnarg!
