### ISSUE TITLE
error when execute apps example

### ISSUE THREAD

**Issue by baakrizal** [RinteRface/bs4Dash#154]
Hi.

i have problem when execute apps example. The error message like that "Warning: Error in : `session$setCurrentTheme()` expects a `bslib::bs_theme()` object."

<img width="1440" alt="Screen Shot 2021-01-07 at 17 05 21" src="https://user-images.githubusercontent.com/76241015/103873456-c87ba000-510a-11eb-8d2f-0e449ad75625.png">

I dont know how to solve it.
Thank you

**Comment by DivadNojnarg** [comment]
Hi,

could you provide me with your session info? I'd like to know what version of shiny, bslib, ...

Thanks

**Comment by alexanderbeatson** [comment]
Same issue, I am working on which code chunk causing that error. 
I use the latest GitHub version of shiny, htmltools, and thematic as stated on GitHub readme.

**Comment by alexanderbeatson** [comment]
Found the issue. 
There are two potential conflicts. 
The first one is _progressBar_ function using from _shinyWidget_ library by default. It can be solved by adding namespace _bs4Dash_. 
The second one is the main cause of this error. You need to delete line 1248 which is _useAutoColor()_. You will lose the auto coloring function in the dashboard, but the dashboard will run without any further issues. I don't have enough time to dig into the source code. Hopefully, contributors will solve that issue soon.

**Comment by DivadNojnarg** [comment]
I'll wait for shiny 1.6.0 to reach CRAN before fixing, as it might break again and again.

**Comment by DivadNojnarg** [comment]
Fixed in latest devel (bslib and shiny on CRAN next week)
