### ISSUE TITLE
Misleading id for tabBox/bs4TabCard

### ISSUE THREAD

**Issue by BenjaminLouis** [RinteRface/bs4Dash#157]
Hi David,

Thanks again for this great work!

I am using `tabBox()` function with the dev version 2.0 and I am wondering why the suffix "_box" id added to the specify id in the function. When I choose an id, I expect to have this exact id to use in css or js file. If a prefix or suffix is added, I think it is extra work in development to check for the ids of html element. 

This is particularly true when using bs4Dash with a framework like golem (ids are already quite long).

But maybe there is a reason to this behavior and I am missing something?

**Comment by DivadNojnarg** [comment]
Hi Benjamin,

Good question! The reason is that `tabBox()` accepts an `id` as parameter to toggle the box state like a classic `box()`. The tabsetpanel must also have an `id` but cannot be the one of box, for uniqueness reasons. That's the reason why I included a prefix.

**Comment by BenjaminLouis** [comment]
Hey,

ok, that's make sense to me ! I didn't notice that the tabsetpanel had the id specify in the function, I was too focus on the whole box.

Oh and I just noticed that there is a note in the help for `tabBox()` that explains it... 😖 I close this issue

Thanks!
