### ISSUE TITLE
customArea doesn't show up on sidebar

### ISSUE THREAD

**Issue by Camil88** [RinteRface/bs4Dash#160]
I'm adding customArea to dashboardSidebar but I can't see any area added on sidebar panel. This is my code: 

      bs4Dash::dashboardSidebar(

       collapsed = TRUE,
       expandOnHover = FALSE,
       customArea = tagList(icon = icon("shipping-fast")),
                      
       bs4Dash::sidebarMenu(id = "sidebarID",
                     bs4Dash::menuItem("XYZ", tabName = "xyz", icon = icon("circle")),
                     bs4Dash::menuItem("WWW", tabName = "www", icon = icon("user-friends"))                                  
                     )
    )

Is it possible at all that you share code of your demo app (https://dgranjon.shinyapps.io/bs4DashDemo/_w_9d9385ce/_w_e1c7b03c/#) here on GitHub? That would make many things easier for me and other users.

**Comment by DivadNojnarg** [comment]
The code is already available here: https://github.com/RinteRface/bs4Dash/blob/master/inst/examples/showcase/app.R

**Comment by Camil88** [comment]
I showed my demo app code and continue this issues in #159

**Comment by DivadNojnarg** [comment]
Fixed in latest devel version
