### ISSUE TITLE
Sidebar issue when starting app. 

### ISSUE THREAD

**Issue by tobiasblasberg** [RinteRface/bs4Dash#161]
I always get an index out of range error when adding `sidebar=dashboardSidebar()` to the dashboardPage. Unfortunately, no example works with the latest code version from Github.

**Comment by shambhu112** [comment]
+1 . I am also getting this issue

**Comment by shambhu112** [comment]
Getting the following error

Error in sidebar$children[[3]] : subscript out of bounds

`
library(bs4Dash)
ui <- dashboardPage(
dashboardHeader(title = "Basic dashboard"),
dashboardSidebar(),
dashboardBody(
# Boxes need to be put in a row (or column)
fluidRow(
box(plotOutput("plot1", height = 250)),

  box(
    title = "Controls",
    sliderInput("slider", "Number of observations:", 1, 100, 50)
  )
)
)
)

server <- function(input, output) {
set.seed(122)
histdata <- rnorm(500)

output$plot1 <- renderPlot({
data <- histdata[seq_len(input$slider)]
hist(data)
})
}

shinyApp(ui, server)
