### ISSUE TITLE
CSS preloader demo not working

### ISSUE THREAD

**Issue by SteEcker** [RinteRface/bs4Dash#164]
Hi thanks for this amazing package!
When I run the CSS preloader demo the loading screen shows, but does not disappear again. 
Here is the code and session info I tried.

```r
library(shiny)
library(bs4Dash)
library(waiter)
shinyApp(
  ui = dashboardPage(
    preloader = list(
      waiter = list(html = tagList(spin_1(), "Loading ..."), color = "#3c8dbc"),
      duration = 5
    ),
    header = dashboardHeader(),
    sidebar = dashboardSidebar(),
    body = dashboardBody(
      actionButton("reload", "Reload")
    ),
    title = "Preloader"
  ),
  server = function(input, output, session) {
    # fake reload
    observeEvent(input$reload, {
      session$reload()
    })
  }
)
```

> R version 3.6.3 (2020-02-29)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19041)
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] waiter_0.2.0       bs4Dash_2.0.0.9000 shiny_1.6.0       
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.6           packrat_0.5.0        digest_0.6.27        later_1.1.0.1        mime_0.9             R6_2.5.0             jsonlite_1.7.2       lifecycle_0.2.0      xtable_1.8-4         magrittr_2.0.1       cachem_1.0.1        
> [12] rlang_0.4.10         promises_1.1.1       jquerylib_0.1.3      bslib_0.2.4          ellipsis_0.3.1       tools_3.6.3          rsconnect_0.8.16     httpuv_1.5.5         fastmap_1.1.0        compiler_3.6.3       htmltools_0.5.1.9000
> [23] sass_0.3.1     

When I add 

> waiter_hide()

to the server function it works.

**Comment by JohnCoene** [comment]
Yes indeed, one has to indicate when to hide the preloader, perhaps this could be clearer in the documentation.

```r
library(shiny)
library(bs4Dash)
library(waiter)

shinyApp(
  ui = dashboardPage(
    preloader = list(
      waiter = list(html = tagList(spin_1(), "Loading ..."), color = "#3c8dbc"),
      duration = 5
    ),
    header = dashboardHeader(),
    sidebar = dashboardSidebar(),
    body = dashboardBody(
      actionButton("reload", "Reload"),
      box(
        plotOutput("plot"),
        status = "warning"
      )
    ),
    title = "Preloader"
  ),
  server = function(input, output, session) {
    output$plot <- renderPlot({
      # simulate long running computations
      Sys.sleep(2)

      on.exit({
        waiter_hide()
      })

      plot(cars)
    
    })
    
    # fake reload
    observeEvent(input$reload, {
      session$reload()
    })
  }
)
```

**Comment by DivadNojnarg** [comment]
The waiter is supposed to hide by itself. I have to check the js code I put. Maybe it’s broken

**Comment by JohnCoene** [comment]
Oh you had that? Nice! Which shiny event to you observe to automatically hide the waiter?

**Comment by DivadNojnarg** [comment]
I used something which was removed in waiter commit 814023bedc355a648c13a0487fadf27195cf098d. I have to update my code.

**Comment by JohnCoene** [comment]
Ah shoot! So sorry. I removed a massive dependency so it's now all custom code, I think it's also the reason for https://github.com/RinteRface/shinyMobile/issues/148 

I'll take a look at the source code of bs4Dash see if I can help fix that.

**Comment by JohnCoene** [comment]
You can `window.hide_waiter(null)` :)

**Comment by DivadNojnarg** [comment]
To be less brutal: `$('.waiter-overlay').fadeOut(1000)`

**Comment by JohnCoene** [comment]
But that gave me an idea that I want to implement in waiter (if possible) throwing this here because I know you may have ideas. 

Ideally this would not be on a timeout but when (probably) the last `*output` was rendered? Or when the reactives flush, I'm not sure but sounds possible.

**Comment by DivadNojnarg** [comment]
Waiting for `shiny:idle`?

**Comment by DivadNojnarg** [comment]
@JohnCoene : what you want is tricky. Imagine an app where there are 3 basic outputs each relying on an input. You could assume that you hide the waiter when all 3 outputs are rendered. You can create a counter and compare it to the value of `Object.keys(Shiny.shinyapp.$bindings).length` (gives you the number of output to render. Don't try `Object.keys(Shiny.shinyapp.$values).length` since values are computed 1 by 1 and its initial value is not the equal to the number of outputs to render) and when they are equal, you hide the waiter:

```javascript
$(function() {
          let counter = 0, hasWaiter;
          
          const hideWaiterCallback = function() { 
            counter +=1;
            console.log(counter);
            hasWaiter = ($('.waiter-overlay').length > 0);
            if (hasWaiter) {
              if (counter === Object.keys(Shiny.shinyapp.$bindings).length) {
                window.hide_waiter(null);
                $(document).trigger('remove_waiter_on_start');
              }
            } 
          }
          
          $(document).on('shiny:value', hideWaiterCallback);
          
          $(document).on('remove_waiter_on_start', function() {
            $(document).off('shiny:value', hideWaiterCallback);
          });
          
        });
```

Moreover, since I don't want this event to trigger when the app is launched, I trigger a custom `remove_waiter_on_start` and deregister the `hideWaiterCallback` from the document. 

It seems to work but what happens, let's say, if an observeEvent runs after a delay to update the first input, which invalidates the first output and triggers a quite long computation? Is it wise the hide the waiter?

**Comment by DivadNojnarg** [comment]
Simple case:

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  waiter_show_on_load(),
  tags$script(
    HTML(
      "$(function() {
          let counter = 0, hasWaiter;
          
          const hideWaiterCallback = function() { 
            counter +=1;
            console.log(counter);
            hasWaiter = ($('.waiter-overlay').length > 0);
            if (hasWaiter) {
              if (counter === Object.keys(Shiny.shinyapp.$bindings).length) {
                window.hide_waiter(null);
                $(document).trigger('remove_waiter_on_start');
              }
            } 
          }
          
          $(document).on('shiny:value', hideWaiterCallback);
          
          $(document).on('remove_waiter_on_start', function() {
            $(document).off('shiny:value', hideWaiterCallback);
          });
          
        });
      "
    )
  ),
  sliderInput("obs", "Number of observations:",
              min = 0, max = 1000, value = 500
  ),
  plotOutput("distPlot")
)

server <- function(input, output, session) {
  output$distPlot <- renderPlot({
    Sys.sleep(6)
    hist(rnorm(input$obs))
  })
}

shinyApp(ui, server)
```

**Comment by DivadNojnarg** [comment]
Possible caveats: does not work for all output elements without bindings actually like `textOutput`, even though this is quite unlikely a `textOutput` takes 18seconds to render. 

With multiple outputs:

```r
library(shiny)

ui <- fluidPage(
  use_waiter(),
  waiter_show_on_load(),
  tags$script(
    HTML(
      "$(function() {
          let counter = 0, hasWaiter;
          
          const hideWaiterCallback = function() { 
            counter +=1;
            console.log(counter);
            hasWaiter = ($('.waiter-overlay').length > 0);
            if (hasWaiter) {
              if (counter === Object.keys(Shiny.shinyapp.$bindings).length) {
                window.hide_waiter(null);
                $(document).trigger('remove_waiter_on_start');
              }
            } 
          }
          
          $(document).on('shiny:value', hideWaiterCallback);
          
          $(document).on('remove_waiter_on_start', function() {
            $(document).off('shiny:value', hideWaiterCallback);
          });
          
        });
      "
    )
  ),
  sliderInput("obs", "Number of observations:",
              min = 0, max = 1000, value = 500
  ),
  plotOutput("distPlot"),
  radioButtons("dist", "Distribution type:",
               c("Normal" = "norm",
                 "Uniform" = "unif",
                 "Log-normal" = "lnorm",
                 "Exponential" = "exp")),
  plotOutput("distPlot2")
)

server <- function(input, output, session) {
  
  output$distPlot2 <- renderPlot({
    Sys.sleep(4)
    dist <- switch(input$dist,
                   norm = rnorm,
                   unif = runif,
                   lnorm = rlnorm,
                   exp = rexp,
                   rnorm)
    
    hist(dist(500))
  })
  
  output$distPlot <- renderPlot({
    Sys.sleep(2)
    hist(rnorm(input$obs))
  })
}

shinyApp(ui, server)
```
