### ISSUE TITLE
Modules with bs4Dash not working properly

### ISSUE THREAD

**Issue by Camil88** [RinteRface/bs4Dash#166]
I have an issue with using modules with bs4Dash. I created one simple ui module to which I copied code from existing `dashboardHeader` section. When I run the app almost all elements in header are not their place, kind of smashed. When I press F12 (in browser) I can see that e.g. some HTML elements are in reverse order (this is what I noticed when I used golem to create app).

I tried adding some extra `tagList` or `tags$div` to my module code but it didn't help. So what's wrong with my way of using module here? Can't I just move ui part from regular code to module as I did here? 

My simple app code is here: https://github.com/Camil88/Shiny_App
When you remove module and copy code back to `dashboardHeader` everything is going smoothly. But when you use module then it crashes. 
Btw I write an app using golem but I don't think it's an issue here - either here (single app) or in golem it doesn't work properly.

**Comment by DavidBarke** [comment]
You need to pass the arguments `skin` and `title` to `dashboardHeader()` instead of `tagList()`, like so:

```r
header = bs4Dash::dashboardHeader(
  skin = "dark",
  title = h5("DEMO app")
  rightUI = mod_headerUI("header_ui")
)
```

An alternative would be to return the result of the call to `dashboardHeader()` from your module.

**Comment by Camil88** [comment]
It works, thanks!
