### ISSUE TITLE
forecast package not work

### ISSUE THREAD

**Issue by baakrizal** [RinteRface/bs4Dash#178]
i have problems when using bs4Dash template.
Some packages not working after run app.
For Example is forecast package. I have error message like this:

Error in get(S3[i, 1L], mode = "function", envir = parent.frame()) : 
  invalid first argument

<img width="1440" alt="Screen Shot 2021-02-16 at 09 56 50" src="https://user-images.githubusercontent.com/76241015/108009393-92043f80-703d-11eb-8b36-90b47d390ee7.png">

Help me please.
Thank you.

**Comment by DivadNojnarg** [comment]
According to the stacktrace, this does not seem related to `{bs4Dash}`:

```r
15.
get(S3[i, 1L], mode = "function", envir = parent.frame()) 
14.
assign_in_namespace("ggplot_build.ggplot", .globals$ggplot_build, 
    "ggplot2") 
13.
ggplot_build_restore() 
12.
ggplot_build_set() 
11.
thematic_on(bg = bg, fg = fg, accent = accent, font = font, sequential = sequential, 
    qualitative = qualitative, inherit = inherit) 
10.
thematic_shiny() 
9.
..stacktraceon..({
    library(shiny)
    library(bs4Dash)
    library(echarts4r) ... 
8.
eval(exprs, envir) 
7.
eval(exprs, envir) 
6.
sourceUTF8(fullpath, envir = new.env(parent = sharedEnv)) 
5.
func(fname, ...) 
4.
appObj() 
3.
shinyAppDir_appR("app.R", appDir, options = options) 
2.
shiny::shinyAppDir(system.file("examples/showcase", package = "bs4Dash", 
    mustWork = TRUE)) at bs4DashGallery.R#22
1.
bs4Dash::bs4DashGallery() 
```

The issue is likely to come with the `{thematic}` version. I fixed it by upgrading to `{thematic}` 0.1.2 from CRAN
