### ISSUE TITLE
Not responsive for mobile apps

### ISSUE THREAD

**Issue by jpara3** [RinteRface/bs4Dash#18]
I have seen that in the example shown here:
http://130.60.24.205/bs4Dash/showcase/classic/
the theme works perfect also on mobile devices, but when you try to do the same, like for example, when you tried to replicate the example shown on:
https://cran.r-project.org/web/packages/bs4Dash/vignettes/bs4Showcase.html
the mobile menu do not works as expected.

I think that is only adding one parameter to the menu, but I dont know how to do it...

**Comment by DivadNojnarg** [comment]
Hi,
this vignette is out of date. Will be fixed in the next CRAN release

**Comment by jpara3** [comment]
Ok, thanks! 

When this new CRAN release will be able?

Thanks!!

**Comment by DivadNojnarg** [comment]
Early January :)

**Comment by jpara3** [comment]
Nice!!!
