### ISSUE TITLE
App always starts in dark mode

### ISSUE THREAD

**Issue by DavidBarke** [RinteRface/bs4Dash#180]
After you added the following lines of code the app always starts in dark mode regardless of argument `skin`:

https://github.com/RinteRface/bs4Dash/blob/6fb8f8175e3672bbb65236d76285c6310197f10c/srcjs/bs4Dash-2.0.0/miscellaneous.js#L314-L317

Was this intended?

**Comment by DivadNojnarg** [comment]
It's a choice based on many user feedback I received. When you specify dark = TRUE, it means you want to start with the dark mode (optionally, you get access to the switch to go back to light). Before you had to say`dark=TRUE` and click on the header switch to activate it. Many people didn't like because it's "one more click to do".  

The `skin` parameter has been left here for compatibility with `{shinydashboard}` but it does nothing (see documentation).

**Comment by stevepowell99** [comment]
sure, but how do I get my app to start in light mode/skin/theme? I just upgraded from 0.6 and I don't really want to get into theming or any of that stuff, I'd just like to continue to use a light theme. Is that possible? thanks!

**Comment by DivadNojnarg** [comment]
To start the app in light mode:

```r
library(shiny)
library(bs4Dash)

shinyApp(
    ui = dashboardPage(
        dark = FALSE,
        header = dashboardHeader(
            title = dashboardBrand(
                title = "My dashboard",
                color = "primary",
                href = "https://adminlte.io/themes/v3",
                image = "https://adminlte.io/themes/v3/dist/img/AdminLTELogo.png"
            )
        ),
        sidebar = dashboardSidebar(),
        body = dashboardBody(
            box(status = "danger"),
            box(status = "primary"),
            box(status = "orange")
        ),
        controlbar = dashboardControlbar(),
        title = "DashboardPage"
    ),
    server = function(input, output) { }
)
```

**Comment by grusheInvestec** [comment]
yes I would like this as well please.

**Comment by DivadNojnarg** [comment]
@DavidBarke : options 2 seems the most reasonable for everyone.

**Comment by shahreyar-abeer** [comment]
So no option to start the app in dark mode and disable the toggle?

**Comment by next-game-solutions** [comment]
Totally agree with @shahreyar-abeer - there needs to be an option to launch in dark mode with a theme toggle hidden. 
What would be the best way to achieve this with the current implementation of `bs4Dash`?

**Comment by next-game-solutions** [comment]
@shahreyar-abeer, in case you are still looking for how to start in the dark mode and disable the theme toggle, the following simple hack works.

In your UI script, use `dark = TRUE` in the `dashboardPage()` call.

Then in your server script place this command: `removeUI(selector = "div:has(> #customSwitch1)", immediate = TRUE)`. This command will find the `div` that contains the `customSwitch1` identifier and remove it.
