### ISSUE TITLE
bs4Dash showcase isn't possible to scroll down

### ISSUE THREAD

**Issue by Andryas** [RinteRface/bs4Dash#181]
Hi, I open the showcase and I notice that it isn't possible scroll down.

![image](https://user-images.githubusercontent.com/24782390/108631026-b2ba0400-7446-11eb-9734-89000bd69a0b.png)

**Comment by DivadNojnarg** [comment]
Hi,

Could you provide more information like your web browser, your session info? Did you try to run `bs4DashGallery` or you ran the app from the online demo?

thanks

**Comment by Andryas** [comment]
Hi, today I reinstalled the bs4Dash and everything works thing.
