### ISSUE TITLE
No Init value for tabBox

### ISSUE THREAD

**Issue by tobiasblasberg** [RinteRface/bs4Dash#195]
Hi there, 

unfortunately, the bs4Dash tabBox is not setting the initial value. 
Without pressing the tabs, the value of tab1 is still NULL and just changing after the first press. 

It worked with the shinadashboard version.

Best,
Tobias

```
      tabBox(
        id = ns("tab1"),
        width = 12,
         tabPanel(title = "t1", "Hello world 1"),
        tabPanel(title = "t2", "Hello world 2")
      ),
```

**Comment by DivadNojnarg** [comment]
Thanks for spotting this. I guess I accidentally removed the JS logic in a previous commit...

**Comment by tobiasblasberg** [comment]
Thank you for the quick fix :)
