### ISSUE TITLE
`popover()` / `tooltip()`: Is the assumption that tag has an id necessary?

### ISSUE THREAD

**Issue by DavidBarke** [RinteRface/bs4Dash#199]
`popover()` and `tooltip()` both assume that the tag they are applied to has an `id` attribute. This should be either documented or maybe it might be possible to bind all tooltips on app start in a singleton with:

```js
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
```

**Comment by DivadNojnarg** [comment]
I think this is already here actually: https://github.com/RinteRface/bs4Dash/blob/master/srcjs/bs4Dash-2.2.0.9000/miscellaneous.js#L118. `dashboardPage` has an __help__ param (https://github.com/RinteRface/bs4Dash/blob/master/R/dashboardPage.R#L21) but it is default to FALSE. You can pass it TRUE.
