### ISSUE TITLE
Create release for version 0.6.0.9000

### ISSUE THREAD

**Issue by diegollarrull** [RinteRface/bs4Dash#202]
There is no release for version 0.6.0.9000, the latest in the 0.x series.
This version has been around for a while and has many fixes w.r.t 0.5.0. 

We've managed to track it down to commit [2f3aedec89c38e2dd876f02f3cb11cb9c1745eac](https://github.com/RinteRface/bs4Dash/commit/2f3aedec89c38e2dd876f02f3cb11cb9c1745eac)

Please check if that is the correct commit to tag the release and, if so, please generate the corresponding release.

Thank you very much in advance. 
Best,

**Comment by DivadNojnarg** [comment]
Here we are: https://github.com/RinteRface/bs4Dash/releases/tag/v0.6.0.9000 ;)

**Comment by diegollarrull** [comment]
Thank you so much @DivadNojnarg !!
