### ISSUE TITLE
Easy-close for bs4CardSidebar

### ISSUE THREAD

**Issue by predict42-patrick** [RinteRface/bs4Dash#208]
It would be a great improvement for the user experience, if it is possible to close a bs4CardSidebar by clicking anywhere else than inside the sidebar. Similar to the not-pinned bs4DashControlbar, which closes automatically.

Maybe the same pinned logic as in the bs4DashControlbar might be the best option for the bs4CardSidebar.

**Comment by predict42-patrick** [comment]
A not perfect but quick workaround via JQuery:

$(document).mouseup(function(e) 
{
    var container = $(".direct-chat-contacts");
    var openContainer = $(".direct-chat-contacts-open");
    // if the target of the click isn't the container nor a descendant of the container and also not if the filter symbol was clicked
    if (!container.is(e.target) && container.has(e.target).length === 0 && $(e.target).parents('.card-tools').length !== 1) 
    {
      openContainer.find("[data-widget='chat-pane-toggle']").click()
    }
});

**Comment by DivadNojnarg** [comment]
Hi. I am fine with your code. I'll put it in the `cardSidebarBinding` input binding. Thanks

**Comment by DivadNojnarg** [comment]
I also added `easyClose` to `boxSidebar` which allows to control the behavior.
