### ISSUE TITLE
bs4TabCard doesn't work

### ISSUE THREAD

**Issue by albgarre** [RinteRface/bs4Dash#221]
Hello,

I believe there is a bug in bs4TabCard. I am not able to run the example within the help page or bs4DashGallery() always with the same error message. I have reduced it to:

![image](https://user-images.githubusercontent.com/11833272/124561470-372d8200-de3e-11eb-8603-040a11e94adc.png)

I believe the problem comes from https://github.com/RinteRface/bs4Dash/blob/207f235fbe848e8373e5fe14b90efb3c4af7b0a9/R/cards.R#L1187

because a couple of lines earlier this element was set to NULL: https://github.com/RinteRface/bs4Dash/blob/207f235fbe848e8373e5fe14b90efb3c4af7b0a9/R/cards.R#L1181

Thanks for taking a look!

**Comment by DivadNojnarg** [comment]
Due to commit from yesterday.
