### ISSUE TITLE
Error in bs4DashPage: unused arguments

### ISSUE THREAD

**Issue by geng-lee** [RinteRface/bs4Dash#223]
## How should I solve this error？

> Error in bs4DashPage(old_school = FALSE, sidebar_min = TRUE, sidebar_collapsed = FALSE,  : 
  unused arguments (old_school = FALSE, sidebar_min = TRUE, sidebar_collapsed = FALSE, navbar = bs4DashNavbar(skin = "light", status = "white", border = TRUE, sidebarIcon = "bars", controlbarIcon = "th", fixed = FALSE, leftUi = bs4DropdownMenu(show = FALSE, align = "left", status = "warning", menuIcon = "envelope-open", src = NULL), rightUi = bs4DropdownMenu(show = FALSE, status = "danger", src = "https://github.com/cc", bs4DropdownMenuItem(message = "message 1", from = "Geng Li", src = "https://cc.github.io/images/avatar.jpg", 
    time = "today", status = "danger", type = "message"))))

**Comment by DivadNojnarg** [comment]
Since v2.0.0, the API was rewritten. Please refer to the documentation to get the list of changes.
