### ISSUE TITLE
Request to add zoom-in/out option to bs4Dash

### ISSUE THREAD

**Issue by jnhyeon** [RinteRface/bs4Dash#229]
Thank you so much for making such a great package.
I am using bs4Dash well for my work.
I am writing to you with a request.

The overall screen of bs4Dash looks bigger.
It would be nice if a function to zoom in or out the entire screen was added.
Of course, I can use the zoom function of your web browser, but I want to display bs4Dash at 80% size when first running.

Thank you.

**Comment by DivadNojnarg** [comment]
This has likely been fixed in v2.0.0 with the fullscreen capability in the navbar:
```r
dashboardPage(
  ..., # other params
  fullscreen = FALSE, # HERE set to TRUE to have the fullscreen toggle
  help = FALSE,
  dark = FALSE,
  scrollToTop = FALSE
)
```
