### ISSUE TITLE
Use `<span>` instead of `<p>` on `bs4SidebarMenuItem`

### ISSUE THREAD

**Issue by yogat3ch** [RinteRface/bs4Dash#230]
Hi @DivadNojnarg,
I'm excited to be using `bs4Dash` for the first time and I'm finding it relatively easy to use. Kudos on a great package for shiny app design!
I have a minor suggestion (and accompanying PR) to use `<span>` tags instead of `<p>` tags for the menu item text due to the newline behavior or paragraph tags when they contain more text.

[Here is the line involved](https://github.com/cran/bs4Dash/blob/36afecd0b7192169f530abcffa16e61d9ab6bec7/R/dashboardSidebar.R#L412)

The resulting change is shown below:
With `<p>` tags, kind of looks weird right?:
![image](https://user-images.githubusercontent.com/32208821/129736395-5ea46cd3-6b03-431d-9a21-d12be9cb3468.png)
With `<span>` tags:
![image](https://user-images.githubusercontent.com/32208821/129736517-250b27ed-1f0f-4eb5-a989-d4377b3238b5.png)

More of what one would expect on a menu.

**Comment by yogat3ch** [comment]
Figured out a workaround with SCSS:
```
@mixin nav-p {
  & .nav-sidebar {
    & .nav-item {
      & .nav-link {
        white-space: normal;
        & p {
          @content;
        }
      }
    }
  }
}
.sidebar-mini {
  &.sidebar-collapse {
    & .main-sidebar {
      &:hover {
        @include nav-p {
          display: inline !important;
        } 
      }
      &:not(:hover) {
        @include nav-p {
          display: none;
        } 
      }
    }
  }
  & .main-sidebar {
    @include nav-p {
      display: inline;
    }
  }
}
```

**Comment by DivadNojnarg** [comment]
Maybe causing #272
