### ISSUE TITLE
bs4Dash::sidebarMenu(collapsed = TRUE) doesn't collapse 

### ISSUE THREAD

**Issue by yogat3ch** [RinteRface/bs4Dash#238]
Hi @DivadNojnarg,
Thanks for chiming in over on echarts4r! We're still troubleshooting those issues!

We noticed that the `collapsed = TRUE` argument doesn't seem to work.

I added 
```
$(document).ready(function(){
var sidebarCollapsed = $(".main-sidebar").attr("data-collapsed");
  if (sidebarCollapsed === "true") {
    // This triggers binding geValue
    $("[data-widget='pushmenu']").PushMenu("toggle");
  }  
});
```
to the bottom of _inst/bs4Dash-2.0.2/bs4Dash.js_ and minified it to overwrite the `min.js` file and it now minimizes on app start as anticipated. 

I didn't do a PR because I thought you might have another location where you have JS that's running on initialization and figured I'd let you add this where you saw fit.

Hope this is helpful!

**Comment by DivadNojnarg** [comment]
Thx. I have to check why it is missing from the JS bundle. Probably a regression I introduced.
