### ISSUE TITLE
Error when running bs4DashGallery() for R versions < 4.1

### ISSUE THREAD

**Issue by FreyGeospatial** [RinteRface/bs4Dash#240]
`> bs4DashGallery()`
```
Loading required namespace: echarts4r
Failed with error:  ‘there is no package called ‘echarts4r’’
Package 'echarts4r' is required to run this function
Loading required namespace: thematic
Loading required namespace: waiter
 Error in library(echarts4r) : there is no package called ‘echarts4r’ 
```

I'm running R 4.0.3, and the `echarts4r` package depends on R >= 4.1, so I can't install it from CRAN. I understand there's not much to be done about it unless you use a different dependency for `bs4DashGallery()` or require users to use R 4.1 but I just thought I'd raise the issue.

**Comment by DivadNojnarg** [comment]
The dependency was removed in latest CRAN release.
