### ISSUE TITLE
bs4Dash UI very strange shaking in browser

### ISSUE THREAD

**Issue by chikao0817** [RinteRface/bs4Dash#245]
Hi ,

bs4Dash is a useful shiny UI package to design goods UI shiny App.
But something strange happened in my experience.

When I use this UI and scrolling in some position.
It would be unusual shaking like this gif.
and nothing happend when scroll the screen up or down. 

![bs4Dash_browser_shaking](https://user-images.githubusercontent.com/47777206/140873353-a61fe7a9-cb28-47dc-a81c-d37b9f02855a.gif)

Any body know why this condition happen??

Thanks.

**Comment by phoebee-h** [comment]
Hi,
I was facing this issue as well, and I happened to see the problem might come from the package "shinycssloaders", which is not obvious lol. To sum up, if you are using `shinycssloaders` :
You can either update the `shinycssloaders` to the latest version OR, change the type in `withSpinner()`.

Thanks to whom have ever posted this issue! Here are the clues that I realize what had happened:
1. https://community.rstudio.com/t/rshiny-ui-swaying-shaking-jumping-up-and-down-on-its-own/118577
2. https://github.com/daattali/shinycssloaders/issues/54
