### ISSUE TITLE
id parameter for bs4SidebarMenu with shinytest

### ISSUE THREAD

**Issue by James-G-Hill** [RinteRface/bs4Dash#249]
The id parameter for `bs4SidebarMenu` was supposed to enable `shinytest` recordings to switch tabs.  See here: https://github.com/RinteRface/bs4Dash/issues/8

However, when I try to implement this in an application, I still get the following error:

'Unable to find input binding for element with id sidebar-sidebar`

(Yeah, I know my sidebar 'id' name is not very original.)

Has anyone been able to get the sidebar menu working with `shinytest`?

**Comment by aylapear** [comment]
I am also having the same issue. I have set the `id` parameter in both the `bs4DashSidebar()` and  `bs4SidebarMenu()` functions and get the error "Unable to find input binding for element with id sidebarmain"

**Comment by DivadNojnarg** [comment]
After discussing with Barett from RStudio the issue appears to be on the shinytest side. Shinytest relies on phantomjs not compatible With Bootstrap 4 and deprecated anyway for many years. Shinytest2 is on the way and should fix that issue.

**Comment by DivadNojnarg** [comment]
See https://github.com/rstudio/shinytest2
