### ISSUE TITLE
Updgrade bootstrap to 4.3.1

### ISSUE THREAD

**Issue by bjornol** [RinteRface/bs4Dash#25]
Is there a millstone in the road map where there is planned to upgrade the bootstrap 4 version to 4.3.1? There are some bugs related to the current version that has been removed in the latest release. I have tested with the new version of bootstrap with bs4dash and haven’t found any major changes. Anyway 4.3.1 fixed my bug in regard to opening modal boxes in windows given bug message: "Object.keys: argument is not an object" which is a bug marked in current version used by bs4Dash

**Comment by DivadNojnarg** [comment]
Thanks for the suggestion. I will open a new branch first to test.

**Comment by bjornol** [comment]
Its in regards to modal boxes. See discussion here https://github.com/twbs/bootstrap/issues/26310

Example code that failed in IE11:
showModal(modalDialog(
    tagList(
    bs4Jumbotron(
        title = 'Bootstrap IE11 failure',
        lead = 'please upgrade bootstrap 4',
        button,
        status = "light"
    )
    ),
    footer = modalButton("Updated bootstrap"),
    size = c("m", "s", "l"),
    easyClose = TRUE,
    fade = FALSE
))
