### ISSUE TITLE
dashboardSidebar is set to dark = FALSE, but loads with black sidebar and white body since yesterday

### ISSUE THREAD

**Issue by franjon** [RinteRface/bs4Dash#250]
Whenever I set the dashboardSidebar to dark = FALSE, expecting the initial white background to load with a toggle button for dark mode, it loads with a black sidebar and a white body. Subsequently, if I toggle between dark and light modes, the correct white color sidebar matches the white body for the light theme and black for dark theme. It's only the initial load of the page where this issue happens. I tried downloading and installing bs4Dash on my personal computer, to try recreating the issue on a completely separate machine and environment than my work computer, and the same thing happened. This also wasn't an issue until yesterday, oddly. I'm having a devil of a time attempting to locate the proper CSS with the Developer tools for a near-term solution.

I should mention, I recreated the issue on my home computer with a completely bare application, no other dependencies or packages loaded: 

library(bs4Dash)
ui <- dashboardPage(
     dashboardHeader(title = 'Test'),
     dashboardSidebar(dark = FALSE),
     dashboardBody()
)
server <- function(input,output) {}
shinyApp(ui,server)

**Comment by DivadNojnarg** [comment]
Hi, `dashboardSidebar` does not have `dark` parameter but `skin`, which may be dark or light: https://github.com/RinteRface/bs4Dash/blob/317efa8369382f40af3b61d1cd4a951cd7dd33fd/R/dashboardSidebar.R#L49.
The `dark` parameter is part of the `dashboardPage` function. It can be TRUE/FALSE or NULL (light + no theme toggle switch).
