### ISSUE TITLE
when box set to collapsed = TRUE, input variables located inside are not initially rendered with renderUI

### ISSUE THREAD

**Issue by FreyGeospatial** [RinteRface/bs4Dash#264]
I have some boxes that contain inputs (text box, checkboxes, etc). These are prepopulated based on input from a database.  The boxes should be collapsed on initial application load.

However, when the boxes are collapsed, the input fields don't seem to be rendered at all until the boxes are opened when using `renderUI`. This is a problem for my application.

```
library(shiny)
library(bs4Dash)

shinyApp(
    ui = dashboardPage(
        dashboardHeader(),
        dashboardSidebar(),
        dashboardBody(
            box(uiOutput("rendered_radio"), collapsed = TRUE),
            box(verbatimTextOutput("myvalue"))
        )
    ),
    server = function(input, output) { 
        
        output$rendered_radio <- renderUI({
            radioButtons(inputId = "test1", 
                          label = "test1",
                          choices = c("value1", "value2"))
        })
        output$myvalue <- renderText(input$test1)
        
        }
)
```

**Comment by DivadNojnarg** [comment]
Not sure this is a bs4Dash issue, more a default Shiny behavior. Any hidden output is suspended. In this case, since the output is actually a programmatically controlled input, reactivity is frozen until it is shown. A way to prevent this is:

```r
outputOptions(output, "rendered_radio", suspendWhenHidden = FALSE)
```

bs4Dash body element are hidden as long as the box is collapsed, which explain why got in this situation.

Does this sound reasonable for you?

**Comment by DivadNojnarg** [comment]
On a side note, I would rather use `updateRadioButtons` once you get the values from the database. Your code will be easier to maintain. You can definitely put dummy values as initial state. 

```r
library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    dashboardHeader(),
    dashboardSidebar(),
    dashboardBody(
      box(radioButtons(inputId = "test1", label = "test1", choices = c("value1", "value2")), collapsed = TRUE),
      box(verbatimTextOutput("myvalue"))
    )
  ),
  server = function(input, output, session) { 
    
    observeEvent(TRUE, {
      # simulate computation
      Sys.sleep(5)
      updateRadioButtons(session, "test1", choices = colnames(mtcars))
    }, once = TRUE)
    output$myvalue <- renderText(input$test1)
    
  }
```

**Comment by FreyGeospatial** [comment]
I see- these solutions do work for me. Thank you! Didn't realize that was default shiny behavior.
