### ISSUE TITLE
Adding tooltip to box header items. 

### ISSUE THREAD

**Issue by fsalemi** [RinteRface/bs4Dash#267]
I have a simple shinyDashbord app with a box that has a sidebar in it. I would like to add tooltip to the sidebar icon in the box header so that when I hover the mouse over the icon, the tooltip shows up. Is that possible?

```
library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    header = dashboardHeader(),
    body = dashboardBody(
      box(
        height = "500px",
        width = 12,
        maximizable = T,
        solidHeader = FALSE,
        collapsible = TRUE,
        sidebar = boxSidebar(
          id = "mycardsidebar",
          width = 30,
          p("Sidebar Content")
        )
      ),
    ),
    sidebar = dashboardSidebar()
  ),
  server = function(input, output, session) {}
)

```
Thanks

**Comment by DivadNojnarg** [comment]
Hi,

This is quite easy to enable First, add the `help = TRUE` to `dashboardPage`. According to the documentation:

> Whether to enable/disable popovers and [tooltip](http://142.93.162.189:8787/help/library/bs4Dash/help/tooltip)s. This allows to seamlessly use tooltip and [popover](http://142.93.162.189:8787/help/library/bs4Dash/help/popover) without having to individually toggle them. Default to FALSE. if TRUE, a help icon is display in the navigation bar.

Second step is to modify the `boxSidebar` tag to change the tooltip text stored in the `data-original-title` attribute:

```r
box_sidebar <- boxSidebar(
  id = "mycardsidebar",
  width = 30,
  p("Sidebar Content")
) 

box_sidebar[[1]]$attribs$`data-original-title` <- "<Your tooltip title>"
```

Whole code:

```r
library(shiny)
library(bs4Dash)

box_sidebar <- boxSidebar(
  id = "mycardsidebar",
  width = 30,
  p("Sidebar Content")
) 

box_sidebar[[1]]$attribs$`data-original-title` <- "<Your tooltip title>"

shinyApp(
  ui = dashboardPage(
    help = TRUE,
    header = dashboardHeader(),
    body = dashboardBody(
      box(
        height = "500px",
        width = 12,
        maximizable = T,
        solidHeader = FALSE,
        collapsible = TRUE,
        sidebar = box_sidebar
      ),
    ),
    sidebar = dashboardSidebar()
  ),
  server = function(input, output, session) {}
)
```

If you want to learn more about customizing HTML tags, you can have a look at this chapter from my book: https://unleash-shiny.rinterface.com/htmltools-overview.html

**Comment by fsalemi** [comment]
Davis, Thank you very much for always coming back with your brilliant solutions. Right after I posted this question, I was able to figure out the help parameter and it's usage, and the tooltip started to show-up. However, it was only showing "More". I also found out that the `data-original-title` is set to "More" initially. However, I did not know how to change this attribute. 
By defining the sidebar outside "ui", you can have access to its attributes and change it accordingly. I now learned it through your response. Thanks for that.
By the way, the reference you recommended is a great reference to study. Do you guys have a paper version of this book available?
Regards

**Comment by DivadNojnarg** [comment]
Available for pre-order at CRC Press: https://www.routledge.com/Outstanding-User-Interfaces-with-Shiny/Granjon/p/book/9780367643652.

**Comment by fsalemi** [comment]
Thanks David, I just preordered.
I also corrected the code for my other question.
