### ISSUE TITLE
bs4DashSidebar() - menu isn't collapsed on screen resize

### ISSUE THREAD

**Issue by maluta** [RinteRface/bs4Dash#27]
My environment it detailed below but I installed bs4Dash using:

`install.packages("bs4Dash")`

And I'm facing this issue when using  bs4DashSidebar() and resize my screen. 

Here an little image to demonstrate that: 

![gif-sidebar](https://user-images.githubusercontent.com/23658/55399510-a9a5ae00-5521-11e9-9ce9-30bf5bb4c7b6.gif)

```
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          5.3                         
year           2019                        
month          03                          
day            11                          
svn rev        76217                       
language       R                           
version.string R version 3.5.3 (2019-03-11)
nickname       Great Truth 
```

Any ideas? Thanks

**Comment by maluta** [comment]
Here my code: 

```
    sidebar = bs4DashSidebar(
    show = TRUE,
    skin = "light",
    status = "",
    title = "xxxx",
    brandColor = "",
    url = "#",
    src = "",
    elevation = 5,
    opacity = 0.8,
    bs4SidebarMenu(
      bs4SidebarHeader(""),
      bs4SidebarMenuItem(
        "Analytics",
        tabName = "item1",
        icon = "chart-bar"
      ),
      bs4SidebarMenuItem(
        "Informações",
        tabName = "item2",
        icon = "id-card"
      )
    )
  )
```

**Comment by DivadNojnarg** [comment]
are you using chrome or firefox?

**Comment by maluta** [comment]
Here a simplified version of my code: 

[code.zip](https://github.com/RinteRface/bs4Dash/files/3074352/code.zip)

Strangely, after update: 

`devtools::install_github("RinteRface/bs4Dash")`

I'm getting an error: 

`ERROR: Couldn't normalize path in 'addResourcePath', with arguments: 'prefix' = 'bootstrap-4.1.0'; 'directoryPath' = ''
 `

**Comment by DivadNojnarg** [comment]
Try to remove the old bs4Dash and install the new version from CRAN.
