### ISSUE TITLE
Strange behaviour with conditionalPanel and columns

### ISSUE THREAD

**Issue by ShinyFabio** [RinteRface/bs4Dash#270]
I'm sorrry, I'm here again. I'm becoming your betatester. 😆 This time I have a problem with columns and conditionalPanels. Here's a reproducible example:

```
library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    title = "Basic Dashboard",
    header = dashboardHeader(
      title = "ShinyDash"),
    
    sidebar = dashboardSidebar(
      sidebarMenu(
        id = "sidebarmenu",
        menuItem("Home", tabName = "home", icon = icon("home"))
        )
    ),
      
    body = dashboardBody(
      tabItems(
        tabItem(
          tabName = "home",
          tabsetPanel(
            tabPanel(
              "tabpanel",
              sidebarLayout(
                sidebarPanel(
                  width = 3,
                  fluidRow(
                    column(6, selectInput("type", "select something", choices = c("1","2"))),
                    
                    conditionalPanel(
                      condition = "input.type == '1'",
                      column(6, selectInput("type1","Type 1.1", choices = "1.1"))
                    ),
                    conditionalPanel(
                      condition = "input.type == '2'",
                      column(4, selectInput("type2","Type 2", choices = "2.1")),
                      column(2, selectInput("type22","Type 2.2", choices = "2.2"))
                    )
                  )
                ),
                mainPanel(h3("mainpanel"))
              )
            ),
            tabPanel("second panel"))
        )
      ) 
    )
  ),

  server = function(input, output) {}
)
```

There's a problem with column width when using conditionalPanel. This problem didn't exist in shinydashboard as you can see in the following pictures. And as you can see, with `{bs4Dash}` the grey background in the sidebarpanel also disappeared.
![Screenshot (153)_LI](https://user-images.githubusercontent.com/78078351/156733206-0911b3fa-41d5-44d7-a44d-a09bd15b96f5.jpg)
![Screenshot (154)_LI](https://user-images.githubusercontent.com/78078351/156733217-92c6d9f0-7959-4b90-8801-a033a2328756.jpg)

**Comment by ShinyFabio** [comment]
Further information: I can solve the problem with the column with `type1` selectInput by writing the conditionalPanel inside the column. But that causes other problems as you can see here. Of course since I moved the conditionalPanel inside the column function, the `column(6)` will be always present.

![Screenshot (155)](https://user-images.githubusercontent.com/78078351/156734848-d669b1cb-319d-4dc2-803d-6cfdb183bd8d.png)


```
library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    title = "Basic Dashboard",
    header = dashboardHeader(
      title = "ShinyDash"),
    
    sidebar = dashboardSidebar(
      sidebarMenu(
        id = "sidebarmenu",
        menuItem("Home", tabName = "home", icon = icon("home"))
        )
    ),
      
    body = dashboardBody(
      tabItems(
        tabItem(
          tabName = "home",
          tabsetPanel(
            tabPanel(
              "tabpanel",
              sidebarLayout(
                sidebarPanel(
                  width = 3,
                  fluidRow(
                    column(6, selectInput("type", "select something", choices = c("1","2"))),
                    
                    column(6,
                           conditionalPanel(
                             condition = "input.type == '1'",
                             selectInput("type1","Type 1.1", choices = "1.1"))
                    ),
                    column(4,
                    conditionalPanel(
                      condition = "input.type == '2'",
                       selectInput("type2","Type 2", choices = "2.1"))),
                    column(2,
                           conditionalPanel(
                             condition = "input.type == '2'",
                             selectInput("type22","Type 2.2", choices = "2.2")))
                    )
                  
                ),
                mainPanel(h3("mainpanel"))
              )
            ),
            tabPanel("due"))
        )
      )

      
    )
  ),

  server = function(input, output) {}
)
```

**Comment by ShinyFabio** [comment]
Anyone?

**Comment by zpio** [comment]
Hi,

I solved it by moving fluid row and widths. I hope this helps you

`library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    title = "Basic Dashboard",
    header = dashboardHeader(
      title = "ShinyDash"),
    
    sidebar = dashboardSidebar(
      sidebarMenu(
        id = "sidebarmenu",
        menuItem("Home", tabName = "home", icon = icon("home"))
      )
    ),
    
    body = dashboardBody(
      tabItems(
        tabItem(
          tabName = "home",
          tabsetPanel(
            tabPanel(
              "tabpanel",
              sidebarLayout(
                sidebarPanel(
                  width = 3,
                  fluidRow(
                    column(12, selectInput("type", "select something", choices = c("1","2")))
                    ),
                  fluidRow(
                    column(6,
                           conditionalPanel(
                             condition = "input.type == '1'",
                             selectInput("type1","Type 1.1", choices = "1.1"))
                    )),
                  
                  fluidRow(
                    column(6,
                           conditionalPanel(
                             condition = "input.type == '2'",
                             selectInput("type2","Type 2", choices = "2.1"))),
                    column(6,
                           conditionalPanel(
                             condition = "input.type == '2'",
                             selectInput("type22","Type 2.2", choices = "2.2")))
                  ),
                    
                  
                ),
                mainPanel(h3("mainpanel"))
              )
            ),
            tabPanel("due"))
        )
      )
      
      
    )
  ),
  
  server = function(input, output) {}
)`


![solve1](https://user-images.githubusercontent.com/55930230/160443224-3c6a879a-5ff5-4c02-9043-74b2c19001f5.PNG)
![solve2](https://user-images.githubusercontent.com/55930230/160443237-92d1e330-2bf2-45e6-93cb-078686f674c9.PNG)

**Comment by ShinyFabio** [comment]
Hello thanks for your reply. However, I wanted that all three of `selectInput()` stay on the same line. I put just a reproducible example, but in my shinyapp these inputs should be all next to each other. Maybe my second comment was misleading. Sticking to the first comment, bs4Dash has problems if the `conditionalPanel()` is outside the `column()`. In your example, the solution is simple, but if I want to use multiple conditionalPanels and columns, like in the first example, I couldn't find a solution. In that case, I think that you have no other solution than putting `conditionalPanel()` outside the `column()`, but that cause the problem with this package.

Look at this picture. It seems that bs4Dash divided the second column two times. Look how ridiculously small the column is. The first column with width = 6, is 205px long. Hence, the column with width = 3 should be the half (~100px) and not 18.5px.

![Screenshot (218)](https://user-images.githubusercontent.com/78078351/160556440-f1a92b35-13f9-44f0-a533-3c45126ac55a.png)

**Comment by zpio** [comment]
Hi, ok, I tried this, looks better:

```
library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    title = "Basic Dashboard",
    header = dashboardHeader(
      title = "ShinyDash"),
    
    sidebar = dashboardSidebar(
      sidebarMenu(
        id = "sidebarmenu",
        menuItem("Home", tabName = "home", icon = icon("home"))
      )
    ),
    
    body = dashboardBody(
      tabItems(
        tabItem(
          tabName = "home",
          tabsetPanel(
            tabPanel(
              "tabpanel",
              sidebarLayout(
                sidebarPanel(
                  width = 3,
                  fluidRow(
                    width=12,
                    column(6,selectInput("type", "select", choices = c("1","2"))),
                    
                    conditionalPanel(
                      condition = "input.type == '1'",
                      column(12, selectInput("type1","Type 1.1", choices = "1.1"))
                    ),
                    conditionalPanel(
                      condition = "input.type == '2'",
                      fluidRow(
                        column(6, selectInput("type2","Type 2.1", choices = "2.1")),
                        column(6, selectInput("type22","Type 2.2", choices = "2.2"))
                      )
                      
                    )
                  )
                ),
                mainPanel(h3("mainpanel"))
              )
            ),
            tabPanel("second panel"))
        )
      ) 
    )
  ),
  
  server = function(input, output) {}
)

```

![resp1](https://user-images.githubusercontent.com/55930230/160699780-e04aca3d-cb52-477e-93ab-5990bbd10efc.PNG)

**Comment by ShinyFabio** [comment]
Good workaround. Starting from your solution I managed to reach a more clear solution.

```
library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    title = "Basic Dashboard",
    header = dashboardHeader(
      title = "ShinyDash"),
    
    sidebar = dashboardSidebar(
      sidebarMenu(
        id = "sidebarmenu",
        menuItem("Home", tabName = "home", icon = icon("home"))
      )
    ),
    
    body = dashboardBody(
      tabItems(
        tabItem(
          tabName = "home",
          tabsetPanel(
            tabPanel(
              "tabpanel",
              sidebarLayout(
                sidebarPanel(style = "background-color: #f5f5f5; border: 1px solid #e3e3e3; padding: 19px",
                  width = 3,
                  fluidRow(
                    column(6,selectInput("type", "select", choices = c("1","2"))),
                    
                    column(6,
                      conditionalPanel(
                        condition = "input.type == '1'",
                        selectInput("type1","Type 1.1", choices = "1.1")
                      ),
                      
                      conditionalPanel(
                        condition = "input.type == '2'",
                        fluidRow(
                          column(6, selectInput("type2","Type 2.1", choices = "2.1")),
                          column(6, selectInput("type22","Type 2.2", choices = "2.2")))
                      )
                    )
                  )
                ),
                mainPanel(h3("mainpanel"))
              )
            ),
            tabPanel("second panel"))
        )
      ) 
    )
  ),
  
  server = function(input, output) {}
)
```

So what I understood is trying to avoid using conditionalPanel outside column and if so, using fluidRow (even if it should not be necessary). However, since with shinydashboard I didn't have this issue, maybe in the future you can have a look about that.
I added also the same styling used in basic shiny sidebar.

**Comment by zpio** [comment]
Excellent, I like your solution.
