### ISSUE TITLE
hiding menuItem text

### ISSUE THREAD

**Issue by dleopold** [RinteRface/bs4Dash#272]
When the sidebar is partially collapsed /  minified in my bs4Dash apps, the first letter or two of the text associated with sidebarMenu / menuItem is visible. I would like only the icon to be visible when the sidebar is in this state, similar to the behavior of the virtual patient simulator example app. It seems like this should be the default behavior, but I can not seem to make it happen. Here is a minimal app from the documentation with a single menuItem:

```
library(bs4Dash)
ui <- dashboardPage(
  dashboardHeader(title = "Basic dashboard"),
  dashboardSidebar(
    sidebarMenu(
          menuItem(text="Home", tabName = "home", icon=icon('home'))
        ),
),
  dashboardBody()
)

server <- function(input, output) {

}

shinyApp(ui, server)
```

**Comment by DivadNojnarg** [comment]
Probably because of this one #230

**Comment by dleopold** [comment]
You are correct. Reverting the tag from <span> to <p> in the browser developer tools causes the behavior I was looking for. Do you think you will change it back? In case anyone else wants a temporary solution, this modified function works for me:

```
menuItem_p <- function(text, ...){
  require(htmltools)
  item <- bs4Dash::menuItem(text=text, ...)
  tagQuery(item)$
    find("span")$
    replaceWith(p(text))$
    allTags()
}
```

**Comment by dleopold** [comment]
I will close the issue since it is solved for me. Thanks.
