### ISSUE TITLE
Is there a way to inactivate how BS4dash handles the click out of the right control bar?

### ISSUE THREAD

**Issue by tdemarchin** [RinteRface/bs4Dash#275]
Hi,

Currently, the control bar collapses when we click outside of it. 
I'd like the control bar to open when I click on a plot. I can toggle it using plot$click but it collapses immediately (because we click outside of it). I'd like to inactivate this behavior, which is controlled by the javascript below. I could delete that piece of code but when the package will be updated, my changes will be erased so i'd like something more robust. Is it possible to add an option to the controlbar to change this behavior?

Btw, it seems they managed to do a similar trick in the example app (https://dgranjon.shinyapps.io/virtual_patient_v2) but I don't have the code so I am not sure how they did it.

Thanks!

>   // The code below hande the click out of the right control bar
>   $(window).click(function(e) { 
>     // There is a potential conflict. This function detect any click outside
>     // the controlbar and close if if it is not pinned. Yet, if we click on an action       // button controlling the controlbar state (see updatebs4Controlbar), it is also outside the controlbar so the toggle event will be triggered twice. The controlbar will never close as shown in https://github.com/RinteRface/bs4Dash/issues/110. Below we make sure to leave the function as soon as a click on a button holding the class action button. This is not really a fix but a reasonable workaround.
>     var isActionButton = $(e.target).hasClass("action-button");
>     if (isActionButton) return null;>       
>     if($("aside.control-sidebar").find(e.target).length === 0) {
>       var pinned = $(".control-sidebar").attr("data-pin");
>       if (pinned === "false" || pinned === undefined) {
>         $("body").removeClass("control-sidebar-slide-open");  
>         // don't forget to refresh the input binding
>         $("#controlbar-toggle").trigger('collapsed.lte.controlsidebar');
>       }
>     }  
>   });

**Comment by DivadNojnarg** [comment]
Yes you can use the `pinned` parameter. If TRUE, the controlbar will stay open even if you click outside.
