### ISSUE TITLE
clock-o icon in bs4Dash timelineItem doesn't exist in Font Awesome 5

### ISSUE THREAD

**Issue by franjon** [RinteRface/bs4Dash#277]
It appears that whenever I add a timelineItem to my bs4Dash, there's a default usage of the clock-o FA icon in the top right corner tied to the "time" argument. No matter what I put in the "time" argument, NULL, blank, string, date/time, etc. that clock-o icon always shows. For every timelineItem, I get this warning in the R console: 
![image](https://user-images.githubusercontent.com/60668379/164040796-28ba34d4-1b9e-4a88-8b74-205debea31fa.png)
So if I have a timelineBlock with many items, I get this warning for each entry. It's more of a nitpick, but it'd be nice if this default could switch to "clock" from "clock-o", which went away with FA 5 I believe.

**Comment by DivadNojnarg** [comment]
This is fixed in the GitHub version. Please download:

```r
remotes::install_github("RinteRface/bs4Dash")
```
