### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by kengcher** [RinteRface/bs4Dash#28]
Hi

How can i find the list of icons available and create new ones if there isn't a suitable one?

Thank you.

**Comment by DivadNojnarg** [comment]
Hi,

bs4Dash imports icons from fontawesome (https://fontawesome.com). Currently, we support the version 5.0.13, whereas font awesome is already in 5.8 ... See https://use.fontawesome.com/releases/v5.0.13/css/all.css for the css code. 

We also support ionicons (https://unpkg.com/ionicons@4.4.2/dist/css/ionicons.min.css) available at https://ionicons.com.

Should you need more icons, you can choose your own favorite library and import any related css in the head of your shiny app, as follows:

```r
shinyApp(
 ui = fluidPage(
  tags$head(
   includeCSS(path "URL_OF_ICONS")
  ),
  # your app code here
 ),
 server = function(input, output) {}
)
```

**Comment by kengcher** [comment]
Thank you!

**Comment by dickoa** [comment]
Hi, 

Any chance we can have a full/short example. I can't to make it work with the [`humicons` R package](https://gitlab.com/dickoa/humicons) (not on CRAN yet) that wraps the [Humanitarian Icons v02](https://thenounproject.com/ochavisual/collection/ocha-humanitarian-icons-v02/).
I can access the CSS from the package to use `includeCSS` but don't know where to put it in a `bs4DashPage` and also don't know what to put on the `icon` param of `bs4SidebarMenuItem`.

In `shinydashboard` or a simple `shiny` app, I can just use `humicons::humicon("food-security")` in place of `shiny::icon("desktop")`

Thanks again for `bs4Dash`

**Comment by DivadNojnarg** [comment]
Hi Ahmadou,

Just put it after the bs4DashPage opening bracket. Unfortunately, The current implementation of bs4DidebarItem does not allow for using other icon libraries: 
```r
bs4SidebarMenuItem <- function(..., tabName = NULL, icon = NULL) {

  shiny::tags$li(
    class = "nav-item",
    shiny::tags$a(
      class = "nav-link",
      id = paste0("tab-", tabName),
      href = paste0("#shiny-tab-", tabName),
      `data-toggle` = "tab",
      `data-value` = tabName,
      shiny::tags$i(class = paste0("nav-icon fa fa-", icon)),
      shiny::tags$p(
        ...
      )
    )
  )
}
```
You could replace the following code
`shiny::tags$i(class = paste0("nav-icon fa fa-", icon))`
with your own icons.

**Comment by dickoa** [comment]
Thanks a lot @DivadNojnarg, it's working. Here is what I did:

```r
llibrary(bs4Dash)
library(shiny)
library(humicons)

bs4SidebarMenuItem2 <- function(..., tabName = NULL, icon = NULL) {

  shiny::tags$li(
    class = "nav-item",
    shiny::tags$a(
      class = "nav-link",
      id = paste0("tab-", tabName),
      href = paste0("#shiny-tab-", tabName),
      `data-toggle` = "tab",
      `data-value` = tabName,
      icon,
      shiny::tags$p(
        ...
      )
    )
  )
}

shiny::shinyApp(
  ui = fluidPage(
    bs4DashPage(
      navbar = bs4DashNavbar(),
      sidebar = bs4DashSidebar(
        skin = "dark",
        bs4SidebarMenu(
          bs4SidebarHeader("Main content"),
          bs4SidebarMenuItem2(
            "Classic theme",
            tabName = "classic",
            icon = humicon("analysis")
          )
        )
      ),
      controlbar = bs4DashControlbar(
        skin = "light"
      ),
      footer = bs4DashFooter(),
      title = "Classic theme",
      body = bs4DashBody(
        bs4TabItems(
          bs4TabItem(
            tabName = "classic",
            fluidRow(
              bs4Box(
                height = "600px",
                title = "Box 1"
              ),
              bs4Box(
                height = "600px",
                title = "Box 2"
              )
            )
          )
        )
      )
    )
  ),
  server = function(input, output) {}
)
```
