### ISSUE TITLE
Unable to display output

### ISSUE THREAD

**Issue by danabban** [RinteRface/bs4Dash#282]
Pretty new to bs4Dash. Thanks for your support.

I have built a minimal UI and server function but the output is not showing. Kindly help point out in the code below what I'm missing

`library(shiny)
library(gapminder)
library(bbplot)
library(tidyverse)
library(bs4Dash)

year_range <- range(gapminder[["year"]])

ui <- dashboardPage(
    header = dashboardHeader(
      title = dashboardBrand(
        title = "LE",
        color = "gray"
      )
      
    ),
    sidebar = dashboardSidebar(
      width = ,
      skin = "light",
      
      sidebarMenu(
        id = "sidemenu",
        
        menuItem(
          "plotme",
          tabName = "plotme",
          icon = icon("sliders")
        )
        
      )
      
    ),
    
    body = dashboardBody(
      tabItem(
        tabItem(
          tabName = "plotme",
          fluidRow(
            column(
              width = 12,
              plotOutput("plotme")
            )
          )
        )
      )
    ),
    
    controlbar = dashboardControlbar(
      collapsed = FALSE,
      pinned = TRUE,
      skin = "light",
      
      controlbarMenu(
        id = "controlbar",
        
        controlbarItem(
        
            title = "Filter:",
            selectInput("continent", "Continent",
                        choices = unique(gapminder$continent)),

          
            selectInput("country", "Country",
                        choices = NULL),
            
            sliderInput("year",
                        "Select The Year Range:",
                        min = year_range[[1]],
                        max = year_range[[2]],
                        value = c(year_range[[1]], year_range[[2]]),
                        sep = "",
                        step = 1)
            
          
        )
        
      )
    ),
)

server <- function(input, output, session) {
  
  continent_data <- reactive({
    gapminder %>%
      filter(continent == input$continent
             & year >= input$year[[1]] | year <= input$year[[2]])
  })
  
  
  observeEvent(continent_data(), {
    freezeReactiveValue(input, "country")
    choices <- unique(continent_data()$country)
    updateSelectInput(session, "country", choices = choices)
  })
  
  country_data <- reactive({
    req(input$continent)
    continent_data() %>%
      filter(country == input$country
             & year >= input$year[[1]] & year <= input$year[[2]])
  })
  
  
  output$plotme <- renderPlot({
    req(input$country)
    ggplot(country_data(), aes(year, lifeExp)) +
      geom_line(colour = "#1380A1", size = 1) +
      geom_hline(yintercept = 0, size = 1, colour="#333333")
  }, res = 96)
  

  
}

shinyApp(ui = ui, server = server)
`

**Comment by DivadNojnarg** [comment]
You made a typo im the UI. The output id should be plotme, like on the server side.

**Comment by danabban** [comment]
Thanks for your prompt response.

Just checked, the id is "plotme" both in the UI and on the server side. Is there somewhere else I need to check?

**Comment by DivadNojnarg** [comment]
Could come from freezeReactiveValue(input, "country"). The plot has a req(input$country). If the value is frozen, nothing happens.

**Comment by DivadNojnarg** [comment]
I see another typo in `dashboardBody`, you use `tabItem` twice. Should be `tabItems(tabItem(...), ...)`. Working code:

```r
library(shiny)
library(gapminder)
library(dplyr)
library(magrittr)
library(ggplot)
library(bbplot)
library(tidyverse)
library(bs4Dash)

year_range <- range(gapminder[["year"]])

ui <- dashboardPage(
  header = dashboardHeader(
    title = dashboardBrand(
      title = "LE",
      color = "gray"
    )
    
  ),
  sidebar = dashboardSidebar(
    width = ,
    skin = "light",
    
    sidebarMenu(
      id = "sidemenu",
      
      menuItem(
        "plotme",
        tabName = "plotme",
        icon = icon("sliders")
      )
      
    )
    
  ),
  
  body = dashboardBody(
    tabItems(
      tabItem(
        tabName = "plotme",
        fluidRow(
          column(
            width = 12,
            plotOutput("plotme")
          )
        )
      )
    )
  ),
  
  controlbar = dashboardControlbar(
    collapsed = FALSE,
    pinned = TRUE,
    skin = "light",
    
    controlbarMenu(
      id = "controlbar",
      
      controlbarItem(
        
        title = "Filter:",
        
        selectInput("country", "Country",
                    choices = NULL),
        selectInput("continent", "Continent",
                    choices = unique(gapminder$continent)),
        
        
        
        
        sliderInput("year",
                    "Select The Year Range:",
                    min = year_range[[1]],
                    max = year_range[[2]],
                    value = c(year_range[[1]], year_range[[2]]),
                    sep = "",
                    step = 1)
        
      )
      
    )
  ),
)

server <- function(input, output, session) {
  
  continent_data <- reactive({
    gapminder %>%
      filter(continent == input$continent
             & year >= input$year[[1]] | year <= input$year[[2]])
  })
  
  observeEvent(continent_data(), {
    #freezeReactiveValue(input, "country")
    choices <- unique(continent_data()$country)
    updateSelectInput(session, "country", choices = choices)
  })
  
  country_data <- reactive({
    req(input$continent)
    continent_data() %>%
      filter(country == input$country
             & year >= input$year[[1]] & year <= input$year[[2]])
  })
  
  output$plotme <- renderPlot({
    req(input$country)
    ggplot(country_data(), aes(year, lifeExp)) +
      geom_line(colour = "#1380A1", size = 1) +
      geom_hline(yintercept = 0, size = 1, colour="#333333")
  }, res = 96)
  
}

shinyApp(ui = ui, server = server)
```

**Comment by danabban** [comment]
Thank you very much. Very helpful
