### ISSUE TITLE
External links in bs4SidebarMenuItem() not opening properly

### ISSUE THREAD

**Issue by veer0318** [RinteRface/bs4Dash#290]
Hi,

I found a small yet annoying bug: I'm using bs4SidebarMenuItem() with href = 'https://www.google.com' (no tabName set) and newTab = T. This doesn't work: the link won't open. I have traced the issue here: 
https://github.com/RinteRface/bs4Dash/blob/master/R/dashboardSidebar.R#L407

Because you set 
`          `data-toggle` = "tab",`
irrespective of whether it is an internal or external URL, external URLs are not loaded because of javascript code interfering.

This fix works and seems to not cause any regressions (AFAIK):
`
`data-toggle`= if (is.null(href)) "tab",
`

Could you put this fix in the source code?

Best,
Harmen

**Comment by DivadNojnarg** [comment]
Good catch. Added to dev.
