### ISSUE TITLE
Navbar stays keeps white background, even when dark mode is selected/toggled. 

### ISSUE THREAD

**Issue by JJohnson-DA** [RinteRface/bs4Dash#293]
I have started transitioning to bs4dash from shinydashboard (because it rocks) but am having quiet the time with this issue. No matter what I have tried I cannot get the main navbar background color to toggle between light and dark mode. It either stays white on both, or stays whatever other color I set it as. Even on a minimal example from the package docs I am having this issue. 

Any advice or help is much appreciated! Package is most recent version 2.1.0, downloaded 2022-06-19.

```r
library(bs4Dash)
ui <- dashboardPage(
    dashboardHeader(title = "Basic dashboard"),
    dashboardSidebar(),
    dashboardBody(
        # Boxes need to be put in a row (or column)
        fluidRow(
            box(plotOutput("plot1", height = 250)),
            box(
                title = "Controls",
                sliderInput("slider", "Number of observations:", 1, 100, 50)
            )
        )
    )
)
server <- function(input, output) {
    set.seed(122)
    histdata <- rnorm(500)
    output$plot1 <- renderPlot({
        data <- histdata[seq_len(input$slider)]
        hist(data)
    })
}
shinyApp(ui, server)
```

![image](https://user-images.githubusercontent.com/89032304/174509060-7c4c9cfd-975a-4742-9e3e-42bb207c0817.png)
![image](https://user-images.githubusercontent.com/89032304/174509084-609e344f-c637-410f-8f80-91a5f16d72ce.png)

**Comment by DivadNojnarg** [comment]
Related to https://github.com/RinteRface/bs4Dash/pull/281#issue-1221922637
