### ISSUE TITLE
tabsetPanel renders below the list of tabPanels when vertical = TRUE

### ISSUE THREAD

**Issue by lucas-alcantara** [RinteRface/bs4Dash#297]
Hello,

I am trying to use the option `vertical= TRUE` within `tabsetPanel`, but event though I can get the vertical list of `tabPanel`, the contents are rendered below the list and not on the right side of it. I thought it could be because of a short width, but nothing changes even with `width = 12`.

Am I missing anything or is there an issue here?

Thanks!

```
library(shiny)
library(bs4Dash)

ui <- dashboardPage(
  header = dashboardHeader(
    title = dashboardBrand(
      title = "My dashboard"
    )
  ),
  sidebar = bs4DashSidebar(),
  controlbar = dashboardControlbar(),
  body = dashboardBody(
    fluidRow(
      column(
        12,
        box(
          width = 12,
          tabsetPanel(
            vertical = TRUE,
            tabPanel("First",
                     tableOutput("iris")
            ),
            tabPanel("Second"),
            tabPanel("Third")
          )
        )
      )
    )
  )
)

server = function(input, output, session) {
  output$iris <- renderTable(iris[1:10,])
}

shinyApp(ui, server)
```

What I get:
![Picture1](https://user-images.githubusercontent.com/73548101/178390705-716c66b5-30ae-4307-b6af-ae1d62f5823c.png)

What I would like to get:
![Picture2](https://user-images.githubusercontent.com/73548101/178390746-8bd3ab5f-4eec-47d1-be0b-b22cded1c4fb.png)

**Comment by DivadNojnarg** [comment]
Fixed in dev branch. Please download:

```r
devtools::install_github("RinteRface/bs4Dash@dev")
```

**Comment by lucas-alcantara** [comment]
Awesome! Worked perfectly, thanks!
