### ISSUE TITLE
Fontawesome 0.3.0 and bs4Dash

### ISSUE THREAD

**Issue by EkkoTheGekko** [RinteRface/bs4Dash#298]
The fontawesome package update to 0.3.0 has switched to fontawesome version 6.1.
This causes some warnings with bs4Dash as some icons have been renamed:
`This Font Awesome icon ('th') does not exist:`
`This Font Awesome icon ('cogs') does not exist:`

Not sure if there are more, but these are the ones I'm getting at the moment.

**Comment by ismirsehregal** [comment]
[Here ](https://github.com/RinteRface/bs4Dash/pull/299) you can find my related PR.

**Comment by sactyr** [comment]
Landed here after a quick google search. While waiting for @ismirsehregal to push the necessary changes I have simply overwritten `icon = shiny::icon("gears")` in `boxSidebar` where my use case is. `'th'` seems a bit more embedded overall (see [link ](https://github.com/RinteRface/bs4Dash/search?q=icon%28%22th%22%29) for quick search but not that easy to replace directly. Hope this helps others who arrived here after googling.

**Comment by ismirsehregal** [comment]
@sactyr I'm not the package maintainer or creator I just provided a pull request which @DivadNojnarg may merge or not. Please see my suggested changes [here](https://github.com/RinteRface/bs4Dash/pull/299/files) it should rename most (hopefully all) icon calls. If this is urgent you can install the modified version via: `devtools::install_github("ismirsehregal/bs4Dash")`.

**Comment by DivadNojnarg** [comment]
Closed in @ismirsehregal 's PR.
