### ISSUE TITLE
Programmatic way to close the "closable" elements?

### ISSUE THREAD

**Issue by rpodcast** [RinteRface/bs4Dash#30]
I've been having a lot of fun exploring the awesome collection of UI elements in the package, and my apps are already becoming much more intuitive to my users!

One element I've been using more often is [`bs4Alert()`](https://rinterface.github.io/bs4Dash/reference/bs4Alert.html) (see screen grab below).  It would be great to have a way to automatically close the alert based on some action in the app or by the user, somewhat like how `shiny::removeModal()` can remove a Shiny modal.  I could do some hacks with `shinyjs` to wrap the alert in a div and hide it based on some event (like hitting that load data button in the example), but a more native solution would make things a lot easier on my side.  Feel free to close if this is not relevant to the package.

![Screen Shot 2019-04-10 at 1 55 17 PM](https://user-images.githubusercontent.com/1043111/55901897-50302580-5b98-11e9-80a0-a10ef262edd8.png)

**Comment by DivadNojnarg** [comment]
Hi Eric,

This is what remains to do for bs4Dash. Until now, most of the releases focused on UI elements and not interactions. There is still a lot to do regarding input bindings in both sidebars, tabSetPanels, ... This is scheduled for the next release, including sub items in the sidebar. Looking forward to this next release!
