### ISSUE TITLE
App Launches Not in Light or Dark Mode But Inbetween

### ISSUE THREAD

**Issue by ApexHeel** [RinteRface/bs4Dash#302]
Issue: Using the simple example version from the documentation and no further customization, the app launches with the sidebar in dark mode and the body in light mode. Toggling the light/dark mode switch fixes it (body changes to dark, toggle again and both change to light). 

Expected behavior: App should launch in light mode not a mix of both.

`[library](https://rdrr.io/r/base/library.html)([shiny](https://shiny.rstudio.com/))
[library](https://rdrr.io/r/base/library.html)([bs4Dash](https://rinterface.github.io/bs4Dash/index.html))

[shinyApp](https://rdrr.io/pkg/shiny/man/shinyApp.html)(
    ui = [dashboardPage](https://rinterface.github.io/bs4Dash/reference/dashboardPage.html)(
        header = [dashboardHeader](https://rinterface.github.io/bs4Dash/reference/dashboardHeader.html)(
            title = [dashboardBrand](https://rinterface.github.io/bs4Dash/reference/dashboardBrand.html)(
                title = "My dashboard",
                color = "primary",
                href = "https://adminlte.io/themes/v3",
                image = "https://adminlte.io/themes/v3/dist/img/AdminLTELogo.png"
            )
        ),
        sidebar = [dashboardSidebar](https://rinterface.github.io/bs4Dash/reference/dashboardSidebar.html)(),
        body = [dashboardBody](https://rinterface.github.io/bs4Dash/reference/dashboardBody.html)(
            [lapply](https://rdrr.io/r/base/lapply.html)([getAdminLTEColors](https://rinterface.github.io/bs4Dash/reference/getAdminLTEColors.html)(), function(color) {
                [box](https://rinterface.github.io/bs4Dash/reference/box.html)(status = color)
            })
        ),
        controlbar = [dashboardControlbar](https://rinterface.github.io/bs4Dash/reference/dashboardControlbar.html)(),
        title = "DashboardPage"
    ),
    server = function(input, output) { }
)`

**Comment by DivadNojnarg** [comment]
Hi. This is the default AdminLTE behavior (also like shinydashboard which does not have dark mode, except through shinydashboardPlus): https://adminlte.io/themes/v3/. I believe this is to provide more contrast with the body. I need to ask the community whether this change is necessary.

**Comment by ApexHeel** [comment]
My thinking is that since the light/dark toggle is present by default and when you toggle to light all switches to light and vice versa with dark that the default presence of all should not be a mix since you can never get back to that if you ever touch the toggle.
