### ISSUE TITLE
bs4dash controlbar icon still displaying while set to NULL

### ISSUE THREAD

**Issue by nali-raz** [RinteRface/bs4Dash#31]
Hello,

The little icon of the `controlbar` is still there although I've set `controlbar = NULL`.

Is there a way to remove it as it's there but we can't even click on it.

<img width="98" alt="Screen Shot 2019-04-24 at 12 51 51" src="https://user-images.githubusercontent.com/30856173/56654185-c56b2280-668f-11e9-9eea-7c8024a5119c.png">

I've found in the example [here](https://rinterface.com/shiny/showcase/ratp/) that they found a way to remove it once the app has been loaded, but I don't know how.

Thanks a lot

**Comment by DivadNojnarg** [comment]
I don’t have acces to computer right now but you could use jQuery to disable it. For instance apply the css property visibility:hidden; at start. In a future release of bs4Dash (with input bindings) this will be done by default.

**Comment by nali-raz** [comment]
Hi,

Thanks, it works well.
