### ISSUE TITLE
tooltip changes style when switching radioButton

### ISSUE THREAD

**Issue by kathi-munk** [RinteRface/bs4Dash#312]
Hello everyone!
I have a bug in my application that whenever I switch my radio buttons and render a new tooltip according to the selection the styling of the tooltip changes. The first time the radiobutton is selected the tooltip has the same look as always (black box, with white font color), but if I select the radio button which was selected beforehand (so e.g. from Radiobutton B back to Radiobutton A) the styling of the toolbox changes to a pretty old fashioned styling with a greyish box and black font color.

Here my code:

```
library(bs4Dash)
library(shiny)

ui <- fluidPage(
  radioButtons("radio", "Radiobuttons", inline = TRUE,
               choices = c("A" = "A", "B" = "B")),
  uiOutput("page")
)

server <- function(input, output, session) {
  observeEvent(input$radio,{
    output$page <- renderUI({
      if(input$radio == "A"){
        bs4Dash::tooltip(
          actionButton("tipA", label = "Tooltip A", icon = icon("question"), style = "info", size = "xs"),
          title = "This is the tooltip for radio button A",
          placement = "right"
        )
      } else {
        bs4Dash::tooltip(
          actionButton("tipB", label = "Tooltip B", icon = icon("question"), style = "info", size = "xs"),
          title = "This is the tooltip for radio button B",
          placement = "right"
        )
      }
    })
  })
}

shinyApp(ui, server)
```

And below images with the tooltip styling:
Correct styling:
![grafik](https://user-images.githubusercontent.com/77802803/191922683-a58ce047-0f62-4720-ac85-e58368680c4f.png)

Then I selected Radiobutton B -> again correct styling and afterwards selected RadioButton A again which led to the following styling:
![grafik](https://user-images.githubusercontent.com/77802803/191922921-90c42e22-c4d4-404a-8a18-80e829415be0.png)

**Comment by DivadNojnarg** [comment]
I would do like this and drop the `renderUI` and also wrap the code in `dashboardPage` otherwise the tooltip won't render properly:

```r
library(shiny)
library(bs4Dash)

ui <- dashboardPage(
  header = dashboardHeader(),
  sidebar = dashboardSidebar(),
  controlbar = dashboardControlbar(),
  footer = dashboardFooter(),
  title = "Tooltip server",
  body = dashboardBody(
    radioButtons("radio", "Radiobuttons", inline = TRUE,
                 choices = c("A" = "A", "B" = "B")),
    actionButton("tip", label = "Tooltip", icon = icon("question"))
  )
)

server <- function(input, output, session) {
  observeEvent(input$radio, {
    removeTooltip(id = "tip")
    addTooltip(
      id = "tip",
      options = list(
        title = sprintf("This is the tooltip for radio button %s", input$radio),
        placement = "right"
      )
    )
  })
}

shinyApp(ui, server)
```

**Comment by kathi-munk** [comment]
Thanks for the response, but I am still not happy with that.
Your code assumes that the defined UI is the main page, but what if I define the UI of a Shiny module which gets dynamically loaded into the main UI page, I do not need a header, sidebar, ... in this module UI. So can this not be done without these components and using a fluidPage?
