### ISSUE TITLE
Creating a card minimized does not display uiOutput when maximized

### ISSUE THREAD

**Issue by wdm0336** [RinteRface/bs4Dash#32]
Running version 0.3.0 of bs4Dash.

In attached code, if the card is created with `collapsed = FALSE`, the card is created and the output is displayed. If however, `collapsed = TRUE`, then the card is created in collapsed mode; however, when the card is maximized, the output is not displayed.

```
library(shiny)
library(bs4Dash)

shiny::shinyApp(
  ui = bs4DashPage(
    old_school = FALSE,
    sidebar_collapsed = FALSE,
    controlbar_collapsed = FALSE,
    title = "Basic Dashboard",
    navbar = bs4DashNavbar(),
    sidebar = bs4DashSidebar(),
    controlbar = bs4DashControlbar(),
    footer = bs4DashFooter(),
    body = bs4DashBody(
      bs4Card(
        title = "item1",
        collapsed = FALSE,
        uiOutput(outputId = "will_this_run")
      )
    )
  ),
  server = function(input, output) {
    output$will_this_run <- renderUI({
      p("It Ran")
    })
  }
)
```

**Comment by DivadNojnarg** [comment]
See https://github.com/RinteRface/bs4Dash/commit/41f466bb27929017d8846f393f017982264f8e81. This issue was probably reintroduced recently. I will fix it ASAP.

**Comment by wdm0336** [comment]
Works now. Thanks.
