### ISSUE TITLE
actionButton label erroneous output "treevew-link"

### ISSUE THREAD

**Issue by echoplaza** [RinteRface/bs4Dash#325]
The actionButton label should read "reset" as that's the supplied label argument, but instead it reads "reset treeview-link". When I move the actionButton outside the menuItem but keep it inside the sidebarMenu, the label displays properly, but I need the actionButton inside the menuItem. 

```
library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    title = "Basic Dashboard",
    header = dashboardHeader(),
    sidebar = dashboardSidebar(width = 300, sidebarMenu( 
      id = "tabs",
      sidebarHeader("Header 1"),
      actionButton(inputId = "reset_open_conf1", label = "reset"),
      menuItem(
        "Item 1",
        tabName = "item1",
        icon = icon("id-card"),
        actionButton(inputId = "reset_open_conf2", label = "reset")
      )
    )),
    controlbar = dashboardControlbar(),
    footer = dashboardFooter(),
    body = dashboardBody()
  ),
  server = function(input, output) {

  }
)
```

**Comment by DivadNojnarg** [comment]
Fixed in the dev branch. Please try and let me know.

**Comment by echoplaza** [comment]
@DivadNojnarg thanks. I'm new to R development and not sure how to install/run the dev package. I tried this: 

install.packages("C:/path/bs4Dash-dev.zip", repos = NULL, type = "source")

but then when I run "library(bs4Dash-dev)  I get: 

Error in library(bs4Dash - dev) : 'package' must be of length 1

So I'd assume I'm doing something wrong but haven't been able to figure out what.
