### ISSUE TITLE
Conflict between useShinyjs(), and bs4DashControlbar

### ISSUE THREAD

**Issue by mabuimo** [RinteRface/bs4Dash#339]
If you write useShinyjs(),  just after ui <- dashboardPage(

and then you remove this block
`  controlbar = bs4DashControlbar(
    disable = TRUE,
  ),`

You get an error.

**Comment by DivadNojnarg** [comment]
Hi,

`useShinyjs()` can only go inside `dashboardBody()` or `tabItem()` (dashboardBody tab element if you have items in the sidebar). All other bs4Dash elements have strict expectations on what item to receive.
