### ISSUE TITLE
Resizable cards

### ISSUE THREAD

**Issue by ivokwee** [RinteRface/bs4Dash#34]
Hi. I was wondering, is resizing of the cards possible or planned? Like in shinyjqui. But in shinyjqui the cards do not snap. Thanks. Great package. Ivo.

**Comment by DivadNojnarg** [comment]
This should be possible: https://github.com/RinteRface/tablerDash is able to do so after some manipulations.

**Comment by DivadNojnarg** [comment]
I am working on this issue now

**Comment by DivadNojnarg** [comment]
closed with commit e97ed9a
