### ISSUE TITLE
bs4TabCard title not aligned and not to the right

### ISSUE THREAD

**Issue by HugoGit39** [RinteRface/bs4Dash#342]
Hi

With you example [here ](https://rinterface.github.io/bs4Dash/reference/tabBox.html)the title is not aligned well with the tabs and is not aligned to the right. The example with [shinydashboard ](https://rstudio.github.io/shinydashboard/structure.html#tabbox)does work well...however if I load bs4dash the issue arises too.

![Capture](https://user-images.githubusercontent.com/60048570/230771639-8a29aa00-9141-4048-b45f-519d02bf836d.JPG)

**Comment by DivadNojnarg** [comment]
Made some progress (sorry I had nearly no time to work on this):

<img width="880" alt="Screenshot 2023-06-05 at 17 20 43" src="https://github.com/RinteRface/bs4Dash/assets/18291543/24fe2568-b2dc-42cd-8b4a-9b1bda58af52">

The vertical alignement is better. Remain the right space between the title and the tabs to fix. I also updated the pills design to have more padding.

**Comment by HugoGit39** [comment]
Looks great @DivadNojnarg !!
