### ISSUE TITLE
Display the help switch but keep tooltips disabled

### ISSUE THREAD

**Issue by akulumbeg** [RinteRface/bs4Dash#343]
Hello! Currently the behavior of dashboardPage()'s "help" parameter is the following:

If help = TRUE, the switch on the top right is shown and enabled.
If help = FALSE, the switch is not shown at all (and obviously disabled)

As the app I am developing is pretty self-explanatory, from the UX/UI perspective, I find it more reasonable to know that there is a help feature (tooltips, popovers), and enable it on-demand if necessary, rather than to have to disable it every time the app is loaded (particularly if you are an experienced user).

This being said, I would like to have it shown but disabled initially, so that a user can turn the popovers on later. Is this possible? 

Thanks!

**Comment by akulumbeg** [comment]
That is exactly as I would imagine it!

**Comment by DivadNojnarg** [comment]
Please test from the dev branch and let me know. I'll push it to CRAN soon.

**Comment by akulumbeg** [comment]
Upon setting to FALSE, it starts with the switch visible and disabled, so that's good. However, regardless, the tooltips still appear. Once I click to enable them and then disable them again, they appear no more. However, I should say that I am using tooltips from the bsplus package, so perhaps that could be the issue. Cannot afford to rewrite the code fully to do more testing though :(

**Comment by DivadNojnarg** [comment]
Yes `{bsplus}` is not compatible with `{bs4Dash}`. I believe it uses Bootstrap 3, while we need Bootstrap 4 (and soon Bootstrap 5).

**Comment by DivadNojnarg** [comment]
Could be a caching issue. Did you reset your web browser cache?

**Comment by akulumbeg** [comment]
Unfortunately, this does not seem to be the issue, tried both on Chrome and Firefox with cache purged.

**Comment by DivadNojnarg** [comment]
Great. I'll close it when released to CRAN.

**Comment by JsLth** [comment]
This currently leaves one option uncovered.

`help = TRUE` **displays** a switch and **enables** tooltips
`help = FALSE` **displays** a switch and **disables** tooltips
`help = NULL` does **not display** a switch and **disables** tooltips

What do we do if we want to **not display** a switch but **enable** tooltips, or in other word expect to have working tooltips by default? Wouldn't it be a good idea to have two arguments `help` and `help_switch`?

**Comment by D3SL** [comment]
shinyJS makes hiding elements pretty trivial.
