### ISSUE TITLE
Sidebar opacity

### ISSUE THREAD

**Issue by Yves-Naly** [RinteRface/bs4Dash#37]
Hi,

I'm facing this issue with the last version of bs4Dash.

When hovering on the sidebar, it appears but it is transparent although I set `opacity = 1`.

You can see a screenshot of the app here
![image](https://user-images.githubusercontent.com/46778239/59500375-9310c100-8e99-11e9-9284-3fef2572e923.png)

And here is what I have for `sidebar` in `bs4dashPage` :

```r
sidebar = bs4DashSidebar(
    title = "Test",
    skin = "light",
    brandColor = "white",
    opacity = 1,
    elevation = 1,
    status = "default",
    url = "example.com",

    # sidebar
    source(file.path("ui", "sidebar_ui.R"), local = TRUE)$value
  )
```

Thanks for your help.

**Comment by Yves-Naly** [comment]
I'm going to close as I think the problem is on my end.
Sorry

**Comment by aliarsalankazmi** [comment]
@Yves-Naly could you say how you resolved the problem, because I am facing it too.

**Comment by aliarsalankazmi** [comment]
Seems it is just a matter of changing the skin to dark:

`bs4DashSidebar(disable = F, title = "Adaa Data Validation Tool", skin = "dark")`
