### ISSUE TITLE
`popover()` doesn't work

### ISSUE THREAD

**Issue by lgnbhl** [RinteRface/bs4Dash#374]
Thanks for this great package.

The `popover()` function doesn't seem to work. I ran the example from the documentation but nothing is showing when clicking on the action button:

```r
# code from: https://rinterface.github.io/bs4Dash/reference/popover.html
library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    header = dashboardHeader(),
    sidebar = dashboardSidebar(),
    controlbar = dashboardControlbar(),
    footer = dashboardFooter(),
    title = "Popover UI",
    body = dashboardBody(
      popover(
        actionButton("goButton", "Click me to see the popover!"),
        title = "My popover",
        placement = "right",
        content = "Vivamus sagittis lacus vel augue laoreet rutrum faucibus."
      )
    )
  ),
  server = function(input, output) {}
)
```

Do you have the same issue?

**Comment by DivadNojnarg** [comment]
Thanks. Sorry this is a documentation issue. If you pass help=TRUE in dashboardPage, popover will show: https://rinterface.github.io/bs4Dash/reference/dashboardPage.html. The doc hasn’t been updated here and still refer to the old way of doing it.

**Comment by lgnbhl** [comment]
Thanks a lot for your quick answer. I see the related documentation is already updated in the GitHub repo. So I close this issue :).
