### ISSUE TITLE
dashboardBrand issues

### ISSUE THREAD

**Issue by onmyojiyys** [RinteRface/bs4Dash#386]
I want to replace the image in dashboardBrand with a local logo picture, but it doesn't seem to work. I'm sure that there is no problem with the relative path between the picture and app.R. Could you please tell me how to use local png pictures in dashboardBrand?
`header = dashboardHeader(
      title = dashboardBrand(
        title = "bs4Dash",
        color = "primary",
        href = "https://www.google.fr",
        image = "./images/logo.png"
      ),
      skin = "light",
      status = "white",
      border = TRUE,
      sidebarIcon = icon("bars"),
      controlbarIcon = icon("th"),
      fixed = FALSE,
      leftUi = tagList(
        dropdownMenu(
          badgeStatus = "info",
          type = "notifications",
          notificationItem(
            inputId = "triggerAction2",
            text = "Error!",
            status = "danger"
          )
        ),
        dropdownMenu(
          badgeStatus = "info",
          type = "tasks",
          taskItem(
            inputId = "triggerAction3",
            text = "My progress",
            color = "orange",
            value = 10
          )
        )
      ),
      rightUi = dropdownMenu(
        badgeStatus = "danger",
        type = "messages",
        messageItem(
          inputId = "triggerAction1",
          message = "message 1",
          from = "Divad Nojnarg",
          image = "https://adminlte.io/themes/v3/dist/img/user3-128x128.jpg",
          time = "today",
          color = "lime"
        )
      )
    )`

![image](https://github.com/user-attachments/assets/1a2a05f7-90ff-4b49-8886-028a477b4138)

**Comment by DivadNojnarg** [comment]
Hi,

That's probably because the image you point to isn't available on the server for the Shiny app. You have to tell shiny about this, for instance you can use `shiny::addResourcePath("assets/images", "<PATH_TO_IMAGES>")` to tell shiny to serve the `PATH_TO_IMAGES` folder at `assets/images`. Then you can use `assets/images` to point to different images in you Shiny app code:

```r
library(shiny)
library(bs4Dash)
library(fresh)

shiny::addResourcePath("assets/images", "<PATH_TO_IMAGES>")

  shinyApp(
    ui = dashboardPage(
      options = NULL,
      header = dashboardHeader(
        title = dashboardBrand(
          title = "My dashboard",
          color = "primary",
          href = "https://adminlte.io/themes/v3",
          image = "assets/images/<IMAGE_FILE>"
        )
      ),
      sidebar = dashboardSidebar(),
      body = dashboardBody(
        box(status = "danger"),
        box(status = "primary"),
        box(status = "orange")
      ),
      controlbar = dashboardControlbar(),
      title = "DashboardPage"
    ),
    server = function(input, output) { }
  )
```

**Comment by onmyojiyys** [comment]
Thanks！I fixed this.
