### ISSUE TITLE
Disable Sidebar & Controlbar

### ISSUE THREAD

**Issue by jamiebono** [RinteRface/bs4Dash#41]
Is there a way to completely disable the sidebar and/or controlbar?

**Comment by DivadNojnarg** [comment]
I am currently working on that ;). Thanks for the suggestion

**Comment by jamiebono** [comment]
Thanks for your hard work on this! I wish I could help more.

**Comment by Duque-de-Sealand** [comment]
Hi, im working with bs4Dash 2.0.2 and the disable argument does not work for the control bar. Its still there. Is there a way to disable the control bar? Because the argument for the sidebar does work.
