### ISSUE TITLE
uiOutput not working when nested in more than two bs4dash containers

### ISSUE THREAD

**Issue by AtchePortillo** [RinteRface/bs4Dash#45]
Here's a version to show the issue I come across working on a bigger app. What I noticed is that when uiOutput is inside more than two bs4Dash containers it wouldn't render the ui. If I replace bas4TabCard with column, the ui works, but I cannot do that in the app I'm working on. Are there other solutions? 

```r
ui <- bs4DashPage(
  
  bs4DashNavbar(),
  
  bs4DashSidebar(),
  
  bs4DashBody(
    bs4TabCard(
      id = "tabcard",
      column(width = 12,
             id = "df",
             bs4TabSetPanel(
               id = "digital",
               side="left",
               bs4TabPanel(width = 6,
                           tabName = 'test',
                           uiOutput("try")
               )
             )
      ))
  ))


server <- function(input, output){
  print("test")
  output$try <- renderUI ({
    print("try")
    column(
      width = 12,
      selectInput(
        inputId = "digital_pathway_insights_channel",
        label = "Choices",
        choices = c("a", "b", "c")
      )
    )
  })
}


shinyApp(ui=ui, server=server)
```

**Comment by DivadNojnarg** [comment]
Hi, 

This is due to several issues in your code. You can't include a bs4TabSetPanel in a bs4TabCard since it already create a bs4TabSetPanel. You just need to pass bs4TabPanel. Besides, the bs4TabPanel does not have a width argument. You also don't need the column wrapper. 

The following code will work:

```r

# get the latest version
remotes::install_github("RinteRface/bs4Dash)

library(shiny)
library(bs4Dash)
ui <- bs4DashPage(
  
  bs4DashNavbar(),
  
  bs4DashSidebar(),
  
  bs4DashBody(
    bs4TabCard(
      id = "tabcard",
      title = "Tab card",
      bs4TabPanel(
        tabName = 'test',
        uiOutput("try")
      )
    )
  )
)


server <- function(input, output){
  output$try <- renderUI({
    column(
      width = 12,
      selectInput(
        inputId = "digital_pathway_insights_channel",
        label = "Choices",
        choices = c("a", "b", "c")
      )
    )
  })
}
shinyApp(ui=ui, server=server)
```

**Comment by AtchePortillo** [comment]
Hi DivadNojnarg, 

Thanks for the solution, however I'm working with a large app that has multiple uis and servers. The current structure uses 4 containers, I revised the code to replicate the container setup I have (bs4TabItems -> bs4TabItem -> bs4TabCard -> bs4TabPanel). The iuouput doesnt work here. 


`library(shiny)
library(bs4Dash)
ui <- bs4DashPage(
  
  bs4DashNavbar(),
  
  bs4DashSidebar(),
  
  bs4DashBody(
    bs4TabItems(
      bs4TabItem(
        bs4TabCard(
          id = "tabcard",
          title = "Tab card",
          bs4TabPanel(
            tabName = 'test',
            uiOutput("try")
          )
        )
      )
    )
  )
)


server <- function(input, output){
  output$try <- renderUI({
    column(
      width = 12,
      selectInput(
        inputId = "digital_pathway_insights_channel",
        label = "Choices",
        choices = c("a", "b", "c")
      )
    )
  })
}
shinyApp(ui=ui, server=server)`

**Comment by gueyenono** [comment]
Did you ever find a solution to this issue? @AtchePortillo

**Comment by DivadNojnarg** [comment]
Update. In recent bs4Dash version, you don't need to wrap the body content in bs4TabItems and bs4TabItem if there are no items in the sidebar:

```r
library(shiny)
library(bs4Dash)
ui <- bs4DashPage(
  
  bs4DashNavbar(),
  
  bs4DashSidebar(),
  
  bs4DashBody(
    bs4TabCard(
      id = "tabcard",
      title = "Tab card",
      bs4TabPanel(
        tabName = 'test',
        uiOutput("try")
      )
    )
  )
)


server <- function(input, output){
  output$try <- renderUI({
    column(
      width = 6,
      selectInput(
        inputId = "digital_pathway_insights_channel",
        label = "Choices",
        choices = c("a", "b", "c")
      )
    )
  })
}
shinyApp(ui=ui, server=server)
```
