### ISSUE TITLE
Control bar not showing top elements when collapsed == FALSE

### ISSUE THREAD

**Issue by wdm0336** [RinteRface/bs4Dash#47]
When a control bar is created and `controlbar_collapsed = FALSE`, then the control bar is created and the top elements are not visible. If the control bar is collapsed and then un-collapsed, the elements appear.

It appears that the elements are hidden underneath the navbar until re-displayed.

using 0.4.0.9000

**Comment by DivadNojnarg** [comment]
Do you mean something like this?

```r
library(shiny)
library(bs4Dash)

shiny::shinyApp(
  ui = dashboardPage(
    controlbar_collapsed = FALSE,
    navbar = dashboardHeader(
      rightUi = bs4DropdownMenu(
        show = TRUE,
        labelText = "!",
        status = "danger",
        src = "http://www.google.fr",
        bs4DropdownMenuItem(
          text = "message 1",
          date = "today"
        ),
        bs4DropdownMenuItem(
          text = "message 2",
          date = "yesterday"
        )
      )
    ),
    sidebar = dashboardSidebar(),
    body = dashboardBody(),
    controlbar = dashboardControlbar(
      skin = "light",
      controlbarMenu(
        side = "left",
        id = "tabsetpanel",
        controlbarItem(
          tabName = "Tab 1",
          br(),
          sliderInput(
            "obs",
            "Number of observations:",
            min = 0,
            max = 1000,
            value = 500
          )
        ),
        controlbarItem(
          tabName = "Tab 2",
          br(),
          checkboxGroupInput(
            "variable",
            "Variables to show:",
            c("Cylinders" = "cyl",
              "Transmission" = "am",
              "Gears" = "gear")
          )
        ),
        controlbarItem(
          tabName = "Tab 3",
          br(),
          selectInput(
            "state",
            "Choose a state:",
            list(`East Coast` = list("NY", "NJ", "CT"),
                 `West Coast` = list("WA", "OR", "CA"),
                 `Midwest` = list("MN", "WI", "IA")
            )
          )
        )
      )
    )
  ),
  server = function(input, output) {
    output$distPlot <- renderPlot({
      hist(rnorm(input$obs))
    })
    
    output$data <- renderTable({
      head(mtcars[, c("mpg", input$variable), drop = FALSE])
    }, rownames = TRUE)
    
    output$result <- renderText({
      paste("You chose", input$state)
    })
  }
)
```

It works for me. Maybe you can send me an example or a screenshot.

**Comment by wdm0336** [comment]
Here is a minimal example. Sorry I didn't include at the onset:

library(shiny)
library(bs4Dash)

shiny::shinyApp(
    ui <- bs4DashPage(
        old_school = FALSE,
        sidebar_collapsed = TRUE,
        controlbar_collapsed = FALSE,
        title = "Control Bar Checkbox Hidden",
        sidebar = bs4DashSidebar(
            title = "Sidebar",
            bs4SidebarMenu(
            )
        ),
        navbar = bs4DashNavbar(
            skin = "light",
            status = "white",
            border = TRUE,
            sidebarIcon = "bars",
            fixed = FALSE,
            tags$a(href="https://github.com/RinteRface/bs4Dash", tags$p("Bs4Dash", style="font-size:40px"))
        ),
        controlbar = bs4DashControlbar(
            skin = "light",
            checkboxInput(inputId = "showVis", label = "Check Me", value = FALSE)
        ),
        body = bs4DashBody(
            bs4TabItems(
                bs4TabItem(
                    tabName = "First_Tab",
                    tags$p("Here is the first tab")
                )
            )
        )
    ),
    server = function(input, output) { }
)

**Comment by DivadNojnarg** [comment]
This is due to the class layout-fixed in the body element. It somehow messes up with the controlbar.
