### ISSUE TITLE
Jumbotron setting btn_name to NULL does not remove the button

### ISSUE THREAD

**Issue by davidlvb** [RinteRface/bs4Dash#49]
Setting btn_name to NULL does not remove the Jumbotron button -- it still appears as a small dark-grey button. (Using the above code as an example)

_Originally posted by @davidlvb in https://github.com/RinteRface/bs4Dash/issues/10#issuecomment-519686717_

**Comment by DivadNojnarg** [comment]
This is being fixed in the next release

**Comment by sciordia** [comment]
Resolved. Both fields must be set to NULL: btnName = NULL, href = NULL

Great!!
