### ISSUE TITLE
Suggestion on Sidebar open on hover

### ISSUE THREAD

**Issue by ResourceX** [RinteRface/bs4Dash#52]
Sometimes, I inadvertently open the sidebar. It would be nice if I could use the bars in the control bar to open or close the sidebar. Remove the open on hover. 

Overall, I love these UI elements and the work you have done here .

Thank you.

**Comment by DivadNojnarg** [comment]
Hi. I will set an option to give the choice instead of removing it.

**Comment by ResourceX** [comment]
Thank you, works great. 

I wanted the page to open with it closed then the user could toggle it open. I used the updatebs4Sidebar function to accomplish what I wanted. I think it is nice actually in that it opens momentarily showing people, then slides away.  For anyone else, here is what I did.

```
if (interactive()) {
 library(shiny)
 library(bs4Dash)

 shiny::shinyApp(
   ui = dashboardPage(
     controlbar_collapsed = FALSE,
     controlbar_overlay = TRUE,
     navbar = dashboardHeader(),
     sidebar = dashboardSidebar(inputId = "sidebar",expand_on_hover=F),
     body = dashboardBody(
       
     )
   ),
   server = function(input, output, session) {

     updatebs4Sidebar(inputId = "sidebar", session = session)
     
   
   }
 )
}
```
