### ISSUE TITLE
id parameter for bs4TabSetPanel?

### ISSUE THREAD

**Issue by juliengrouillet** [RinteRface/bs4Dash#62]
Hi, 

Similar to https://github.com/RinteRface/bs4Dash/issues/8, it would be fantastic if bs4TabSetPanel would have an id parameter so that we can detect which bs4TabPanel is currently active and trigger events (like ://stackoverflow.com/questions/23243454/how-to-use-tabpanel-as-input-in-r-shiny).

Are there plans to add an id parameter to bs4TabSetPanel as well in the future?

Thanks for the awesome work on bs4Dash!

Julien

**Comment by DivadNojnarg** [comment]
Hi Julien,

thanks. I think you are using the CRAN version. The dev version on github has this feature:

```r
bs4TabSetPanel <- function(..., id, side, status = NULL, tabStatus = NULL, 
                           .list = NULL, vertical = FALSE) {
```

**Comment by juliengrouillet** [comment]
Thank you David, that's great news!
Do you have a CRAN release target date? I'm mostly using shiny on offline
servers with a private CRAN mirror (But I can probably find a workaround
until it is released to CRAN).
Merci encore pour ton travail sur ce package!
Julien

**Comment by DivadNojnarg** [comment]
End November

**Comment by juliengrouillet** [comment]
Cool, looking forward to the CRAN release!
Cheers,
Julien

**Comment by juliengrouillet** [comment]
Hi,

I spent a few hours on this, but can't find a way to detect the active tab using bs4dash. 

Here's a standard shiny implementation that works:
`
library(shiny)

if (interactive()) {
  
  ui <- shiny::fluidPage(
    textOutput("text_out"),
    tabsetPanel(id = "tab",
                tabPanel(title = "tab 1"),
                tabPanel(title = "tab 2")
    ))
  
  server <- function(input, output, session) {
    output$text_out <- renderText({ 
      paste("You have selected", input$tab)
    })
  }
  
  shinyApp(ui, server)
}

`

But the bs4dash counterpart doesn't work (I'm using the CRAN version 0.5.0):

`

library(shiny)
library(bs4dash)

if (interactive()) {
  
  ui <- bs4Dash::bs4DashPage(
    textOutput("text_out"),
    bs4Dash::bs4TabSetPanel(side = "left", 
                            id = "tab",
                            
                            bs4Dash::bs4TabPanel(id = "tab1", tabName = "tab1"),
                            bs4Dash::bs4TabPanel(id = "tab2", tabName = "tab2")
    ))
  
  server <- function(input, output, session) {
    output$text_out <- renderText({ 
      paste("You have selected", input$tab)
    })
  }
  
  shinyApp(ui, server)
}
`

Any idea of what I'm doing wrong?

Thanks for your help,

Julien
