### ISSUE TITLE
Suggestion to make bs4DashPage updatable from server

### ISSUE THREAD

**Issue by analytichealth** [RinteRface/bs4Dash#67]
The old_school theme looks great but it would be nice if users could toggle this on or off. Maybe I have missed how to do this?
Relating to the article here: https://rinterface.github.io/bs4Dash/articles/bs4Themes.html
Thanks

**Comment by DivadNojnarg** [comment]
Hi, in practice this situation is a bit complex. Setting the old school theme requires to dynamically change css dependencies. I am not sure this is possible.

**Comment by analytichealth** [comment]
Thanks for checking, no problem
