### ISSUE TITLE
Customizing aspect for icons in the dashbar

### ISSUE THREAD

**Issue by federicomarini** [RinteRface/bs4Dash#70]
Hi David,

referring to https://github.com/RinteRface/bs4Dash/issues/2:

It would be very nice to have control over the icons of the navbar controlling the sideBar and controlBar. Simplest form would be to have the color changed - black on dark skin is not really visible.

Thanks in advance!

**Comment by federicomarini** [comment]
Thanks David!
I am missing the location where I can set the color (e.g. "white"), where should I change that?

**Comment by DivadNojnarg** [comment]
Now it is automatically handle based on the nabber skin parameter. If you chose light, icons will have a grey background. If dark, they will have a sort of white background:

```r
library(shiny)
library(bs4Dash)
 
 shiny::shinyApp(
   ui = bs4DashPage(
     navbar = bs4DashNavbar(
      skin = "dark",
      rightUi = bs4DropdownMenu(
       show = TRUE,
       labelText = "!",
       status = "danger",
       src = "http://www.google.fr",
       bs4DropdownMenuItem(
        message = "message 1",
        time = "today",
        type = "notification"
       ),
       bs4DropdownMenuItem(
        message = "message 2",
        time = "yesterday",
        type = "notification"
       )
      )
     ),
     sidebar = bs4DashSidebar(),
     controlbar = bs4DashControlbar(),
     footer = bs4DashFooter(),
     title = "test",
     body = bs4DashBody()
   ),
   server = function(input, output) {}
 )
```

**Comment by federicomarini** [comment]
Neat. Thanks again!
