### ISSUE TITLE
BS4 Progress Bar min/max don't appear to be working

### ISSUE THREAD

**Issue by helixjason** [RinteRface/bs4Dash#75]
Seeing an issue with the current bs4progress bars, the min/max don't appear to be affecting the progress bar as it is represented by value.

Checked out the current bs4 demo as well, while the code shows different values for the progress bars on the user card type 2, the progress bars themselves are of the same length.  It appears to be stuck in a 0-100 scale.
bs4UserCard(
      type = 2,
      src = "https://adminlte.io/themes/AdminLTE/dist/img/user7-128x128.jpg",
      status = "success",
      imageElevation = 4,
      title = "User card type 2",
      subtitle = "a subtitle here",
      bs4ProgressBar(
        **value = 5,**
        striped = FALSE,
        status = "info"
      ),
      bs4ProgressBar(
        **value = 20**,
        striped = TRUE,
        status = "warning

![image](https://user-images.githubusercontent.com/46255580/70857898-74c16780-1eb4-11ea-98d8-380aa66e1277.png)

**Comment by DivadNojnarg** [comment]
> aria-valuenow, aria-valuemin and aria-valuemax are meta-datas. The progress bar style is not dependent on their value.

Below this is how you would update the progress bar:

```r
library(shiny)
library(bs4Dash)

shiny::shinyApp(
  ui = bs4DashPage(
    navbar = bs4DashNavbar(),
    sidebar = bs4DashSidebar(),
    controlbar = bs4DashControlbar(),
    footer = bs4DashFooter(),
    title = "test",
    body = bs4DashBody(
      
      tags$head(
        tags$script(
          "$(function () {
            Shiny.addCustomMessageHandler('updateProgress', function(message) {
              console.log(message);
              $('.progress-bar').each(function() {
                var min = $(this).attr('aria-valuemin');
                $(this).attr('aria-valuemax', message.valueMax);
                $(this).attr('aria-valuenow', message.valueNow);
                var size = (message.valueNow - min) * 100 / (message.valueMax - min);
                $(this).css('width', size +'%');
                $(this).html(message.valueNow +'%');
              });
            });
           });
          "
        )
      ),
      
      bs4Card(
        title = "Progress bars",
        actionButton("update_bar", "Update Progress"),
        bs4ProgressBar(
          value = 25,
          striped = TRUE,
          status = "warning",
          label = "25%"
        ),
        footer = fluidRow(
          align = "center",
          sliderInput("max", "Max", 0, 100, 100),
          numericInput("value", "value", 10)
        )
      )
    )
  ),
  server = function(input, output, session) {
    observeEvent(c(input$value, input$max), {
      if (input$value > input$max)
        updateNumericInput(
          session, 
          inputId = "value", 
          value = min(input$value, input$max)
        )
    })
    
    observeEvent(input$update_bar, {
      message <- list(valueMax = input$max, valueNow = input$value)
      session$sendCustomMessage(type = "updateProgress", message)
    })
    
  }
)
```

**Comment by DivadNojnarg** [comment]
Note also the demo should be updated. It uses the previous version which is not correct
