### ISSUE TITLE
A descriptionBlockOutput() element would be ideal [feature request]

### ISSUE THREAD

**Issue by gueyenono** [RinteRface/bs4Dash#87]
According to the `bs4Dash` gallery, `descriptionBlock()` is an element suitable for displaying statistics and as such, it should have and its own `***Output()` element. This is because the statistics to display may be dynamic and not static. My current solution is  to create the `bs4Card` that contains the `descriptionBlock()` in a module. This way, I can compute the dynamic statistics outside the module and then pass them to the module UI.

I am not sure how hard it would be to implement a `descriptionBlockOutput()` since a `descriptionBlock` is embedded inside another UI element, but I thought I would just mention the suggestion.

**Comment by gueyenono** [comment]
I am not sure why I did not think about it earlier, but I think I can simply do it with renderUI(). I'll test it out whenever possible and then close the issue if it works as expected.

**Comment by analytichealth** [comment]
Did you get this to work @gueyenono ? I tried with renderUI but the formats get affected.

**Comment by gueyenono** [comment]
@analytichealth For the life of me, I did not see your question when you asked it. It is probably too late now but yes, I got it to work actually using renderUI. Maybe your use case is more complex than mine, but I did not encounter any formatting issue.
