### ISSUE TITLE
bs4TabSetPanel only showing active panel

### ISSUE THREAD

**Issue by FredericKruger** [RinteRface/bs4Dash#96]
I have an issue with bs4TabSetPanel. When I define 2 tabs, it will only ever show the content of the first tab.
Here is my code: 
`bs4TabSetPanel(
    id = "querryTab.TabPanel",
    side = "left",
    bs4TabPanel( tabName = "DB Model", active = TRUE,
                 "Content 1"
    ),
    bs4TabPanel( tabName = "Querry", active = FALSE,
      "Content 2"
    )
  )`

![image](https://user-images.githubusercontent.com/11213402/76542322-b6928780-647c-11ea-850b-8d96748daee6.png)

![image](https://user-images.githubusercontent.com/11213402/76542364-c1e5b300-647c-11ea-9969-e85b3f35eee2.png)

I have attached 2 screenshots to show the issue.
Thank you for your help.

F

**Comment by DivadNojnarg** [comment]
I is probably because you named your tabsetpanel id with a dot: "querryTab.TabPanel".
The point is that you should avoid using ., # and any other characters that might be used by jQuery or CSS.

**Comment by DivadNojnarg** [comment]
An broken example ( I added a . in the tablet id):

```r
library(bs4Dash)


library(shiny)
library(bs4Dash)

shiny::shinyApp(
  ui = bs4DashPage(
    navbar = bs4DashNavbar(),
    sidebar = bs4DashSidebar(),
    controlbar = bs4DashControlbar(),
    footer = bs4DashFooter(),
    title = "test",
    body = bs4DashBody(
      
      # manually inserted panels
      bs4TabSetPanel(
        id = "tabcard.1",
        side = "left",
        bs4TabPanel(
          tabName = "Tab 1", 
          active = FALSE,
          "Content 1"
        ),
        bs4TabPanel(
          tabName = "Tab 2", 
          active = TRUE,
          "Content 2"
        ),
        bs4TabPanel(
          tabName = "Tab 3", 
          active = FALSE,
          "Content 3"
        )
      )
    )
  ),
  server = function(input, output) {}
)
```

If I remove it, it works as expected:

```r
library(shiny)
library(bs4Dash)

shiny::shinyApp(
  ui = bs4DashPage(
    navbar = bs4DashNavbar(),
    sidebar = bs4DashSidebar(),
    controlbar = bs4DashControlbar(),
    footer = bs4DashFooter(),
    title = "test",
    body = bs4DashBody(
      
      # manually inserted panels
      bs4TabSetPanel(
        id = "tabcard",
        side = "left",
        bs4TabPanel(
          tabName = "Tab 1", 
          active = FALSE,
          "Content 1"
        ),
        bs4TabPanel(
          tabName = "Tab 2", 
          active = TRUE,
          "Content 2"
        ),
        bs4TabPanel(
          tabName = "Tab 3", 
          active = FALSE,
          "Content 3"
        )
      )
    )
  ),
  server = function(input, output) {}
)
```
